### ISSUE TITLE
Zotero UI theme

### ISSUE THREAD

**Issue by linxule** [argenos/zotero-mdnotes#1]
This is more of a related question. sorry for posting this as an issue here. As I was watching your demo, I noticed that your Zotero UI's dark theme. Would you be able to share how you configured the dark theme?

**Comment by juandpinto** [comment]
Also _very_ interested here in how you configured that beautiful dark theme. @linxule, were you able to figure this out?

**Comment by argenos** [comment]
I'm using a Nord theme in Ubuntu 18.04: https://github.com/EliverLara/Nordic
