### ISSUE TITLE
PDF Table of Contents - Missing Links

### ISSUE THREAD

**Issue by AwkwardSandwich** [argenos/zotero-mdnotes#10]
Hello,

Thank you for this add-on, it has become an important part of my reading workflow and habit.

I like to extract Table of Contents from long PDFs into my zotero notes using zotfile, to help structure my notes.
As you know, "Batch export to markdown" doesn't export the ToC extracted by zotfile. As a workaround, I create a new note item, and copy-paste the ToC into it.

The resulting "Batch export to markdown" only converts one link out of two, in alternation.

**Example output:**
```
[Chapter 1](zotero://open-pdf/0_XXXXXXXX/68)
Chapter 2
[Chapter 3](zotero://open-pdf/0_XXXXXXXX/106)
Chapter 4
[Chapter 5](zotero://open-pdf/0_XXXXXXXX/147)
```
The links are definitely there in the note created by zotfile, and are retained after I paste them in the new note item.  From the zotero notes, I can click and open all of the PDF chapters.

Is there a possible fix for the output to consistently generate links or, alternatively, would it be possible to have the option to extract the PDF ToC when available?

Thank you!

**Comment by argenos** [comment]
I was able to reproduce it, but I'm afraid it might be something related to the pasting into the note that is formatting the contents in a way that the regex is not catching them correctly. I'll have to see if I can get the TOC from Zotfile's interfaces.

In the meantime, in case it helps, what I've done to structure notes (based on the `zotero-roam-export` plugin) is use the underline option. Any highlights that are underlined will be exported as a H4 heading, if this is the PDF:

![image](https://user-images.githubusercontent.com/5426039/92406216-bdead300-f137-11ea-8ac9-8f28a4b10c7c.png)

This is the Zotero note:
![image](https://user-images.githubusercontent.com/5426039/92406294-f7234300-f137-11ea-88e7-5baae0ba6f30.png)


And this is how the export looks:
![image](https://user-images.githubusercontent.com/5426039/92406427-479aa080-f138-11ea-9b21-7db766d6cba2.png)

**Comment by AwkwardSandwich** [comment]
Great! Thank you for this workaround, I just tested it and it is even better than what I was hoping to do.
