### ISSUE TITLE
Allow choice of character to replace space

### ISSUE THREAD

**Issue by Jmuccigr** [argenos/zotero-mdnotes#101]
**Is your feature request related to a problem? Please describe.**

Not a problem as much as a preference. Right now spaces in various places (e.g., tags) get converted to dashes when "remove_spaces" is true.

**Describe the solution you'd like**

I'd like the option of choosing which character the space gets replaced by. I prefer an underscore, but I can't set that - which is perhaps ironic, given its use in mdnotes' own preferences. :-)

**Comment by astroHaoPeng** [comment]
Something like 
```
extensions.mdnotes.tags.remove_spaces = "true"
extensions.mdnotes.tags.replace_space_by = "-"
```
will be great.
