### ISSUE TITLE
Image missing when exporting the annotations generated by zotero beta into markdown file

### ISSUE THREAD

**Issue by LamFTS** [argenos/zotero-mdnotes#105]
I am currently reading and taking note using the bulid-in pdf reader of zotero beta (5.0.97-beta.29+2fd46157f), and this build-in pdf reader is capable to generate whatever I marked or writed in the pdf and even image of the area capture of the article into an annotations which is the note, but when I trying to export this annotations into markdown file, the image in the annotations fails to appear in the markdown file, that would be of great convience to taking markdown note if this problem can be solved.

**Comment by argenos** [comment]
The beta is not supported just yet. Please see #62 and https://github.com/argenos/zotero-mdnotes/discussions/77
