### ISSUE TITLE
EPUB file support

### ISSUE THREAD

**Issue by veradrawer** [argenos/zotero-mdnotes#107]
To my surprise the addon doesn't work with epub files. Is support being considered?

Alternately, what is the currently recommended workflow for extracting colored highlights from epub files?

Thanks in advance.

**Comment by argenos** [comment]
Mdnotes exports existing Zotero notes. Do you mean you want to extract annotations from EPUBs? If that's the case, that's a feature request for Zotfile/Zotero beta.

**Comment by veradrawer** [comment]
You are right. This was not the right place to ask, sorry.
