### ISSUE TITLE
exported note having escaped characters

### ISSUE THREAD

**Issue by Caffa** [argenos/zotero-mdnotes#115]
**Describe the bug**
I have had issues with the exported note having escaped characters like
\[\[Field\]\] and \- \[ \] although I have disabled HTML conversion in obsidian and am using mdnotes 0.2.0-alpha4 .

**To Reproduce**
1. Extract annotations from highlighted pdf
2. Option click parent item and select mdnotes option to have full export note 
3. In obsidian you will see something like this:
`
**Extracted Annotations**

> \[\[Challenges\]\] <span style="background-color: rgba(56,229,255,.25);"><strong>(Cyan)</strong> - important considerations of real-world communication networks, such as limits on bandwidth.</span>

important considerations of real-world communication  
networks, such as limits on bandwidth.

> \[\[Approach\]\] <span style="background-color: rgba(255,209,0,.25);"><strong>(Yellow)</strong> - we propose an approach to learning sparse discrete communication through backpropagation in the context of MARL, in which agents are incentivized to communicate as little as possible while still achieving high reward.</span>

we propose an approach to learning sparse discrete communication  
through backpropagation in the context of MARL, in which  
agents are incentivized to communicate as little as possible  
while still achieving high reward.

> \- \[ \] #litreview <span style="background-color: rgba(106,217,40,.25);"><strong>(Green)</strong> - Building on top of our prior work on differentiable discrete communication learning,</span>

Building on top of our  
prior work on differentiable discrete communication learning,

> \[\[Approach\]\] <span style="background-color: rgba(255,209,0,.25);"><strong>(Yellow)</strong> - we develop a regularization-inspired message-length penalty term, that encourages agents to send shorter messages and avoid unnecessary communications.</span>`

**Expected behavior**
I expected an export without the escape characters
**Screenshots**
Here are screenshots of the md file in obsidian
![image](https://user-images.githubusercontent.com/1797721/126208725-dafcabce-3065-49a0-b779-56e8ae2597a5.png)
![image](https://user-images.githubusercontent.com/1797721/126208753-39f4da9e-2a87-45aa-9f2a-f43de846963a.png)

and the same annotations in Zotero
![image](https://user-images.githubusercontent.com/1797721/126209491-84384652-5797-4492-af64-f32b45830796.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur, Version 11.4
 - Zotero version: [v5.0.96.2]
 - Mdnotes version: [ v0.1.3] I downloaded the 0.2.0 alpha 4 from releases but when installed, the version number shown is 0.1.3
 - Zotfile version: [v5.0.16]
 - BetterBibtex version: [v5.4.25]

**Additional context**
Also mentioned on https://forum.obsidian.md/t/zotero-zotfile-mdnotes-obsidian-dataview-workflow/15536/39?u=caffae

Here are my settings in Zotero
![image](https://user-images.githubusercontent.com/1797721/126209347-c2d0b4a1-0c07-4929-85be-ae134ba09dc0.png)
![image](https://user-images.githubusercontent.com/1797721/126209396-427d2d56-e370-4cb6-8049-42a65410bcb2.png)

**Comment by argenos** [comment]
Oh I think I know what's wrong! The order in which you apply the tags matter, the `%(color)` placeholder gets converted to a `<span>` which is left intact by mdnotes (we don't want to translate that bit of HTML to markdown, so you can keep the coloured backgrounds if you use them). I believe if you move the `%(color)` placeholder outside the bold `<b>` tag, there should be no escaping of wiki links any more.

**Comment by Caffa** [comment]
I have changed as follows:
![image](https://user-images.githubusercontent.com/1797721/126751752-8f192bea-50f0-4aeb-bbde-4dac57044c1a.png)
but it still results in escaped wiki-links
![image](https://user-images.githubusercontent.com/1797721/126751796-86d5934b-9064-4dcd-a414-4ca8c681e00d.png)

I am not sure if this was what you meant? by moving the color out
