### ISSUE TITLE
Template for own Notes file

### ISSUE THREAD

**Issue by hwongbaul** [argenos/zotero-mdnotes#12]
I would like another feature if possible: 

an option that allow customed content of Notes file.

## Example:

`preferences` -> `note file setting`:
Custom Format: 
```
### Research Question

### Hypotheses

### Methods/Measures

### Key Findings
```

## Result:

![image](https://user-images.githubusercontent.com/8535390/92679859-2e723980-f35c-11ea-85d8-08c6277c9404.png)

**Comment by argenos** [comment]
@hwongbaul I added something for this in #35, I'll probably release the new version on the weekend, but I already uploaded an xpi in the linked PR in case you want to test beforehand.
