### ISSUE TITLE
Export all notes in a collection as individual markdown files

### ISSUE THREAD

**Issue by cjpoor** [argenos/zotero-mdnotes#123]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
At present, as far as I can see, mdnotes can only be used on one item at a time by mouse clicking on the item and using the context menu which mdnotes is added to (but it is only added to the context menu for items, not collections).
What I am wanting to do is export all notes in a collection or library as individual .md files without having to click on every item.
I am using a workaround script to split selected notes dragged to a .txt file.
The BetterBibTeX Collected Notes export translator can be used on collections and libraries and can export all notes but only as a single file. I know these plugins use a different API from the export translators (and I see that you say the API is changing rapidly), but is it possible to add mdnotes to the context menu when clicking on collections and libraries to allow bulk export of markdown notes?

**Additional context**
See the recent comments in this discussion:
https://github.com/retorquere/zotero-better-bibtex/issues/1878

**Comment by argenos** [comment]
This should already be possible to a degree I think... have you tried selecting them with shift, then using right-click and export to markdown? 

If you want to export all contents (that is the metadata AND all Zotero notes - the yellow ones), selecting the collection (or multiple top level items with shift) and right-click with `Batch export to markdown` should export all of them.

**Comment by cjpoor** [comment]
What I am wanting to do is export all notes in a collection or library as individual .md files without having to click on every item.
I know that it is possible to export .md notes from multiple items by Ctrl-clicking each one and then right-clicking on one and then doing mdnotes export. However it doesn't seem possible to right click on a collection (in the left pane where My Library is - see attached
![Screenshot from 2021-08-21 09-41-25](https://user-images.githubusercontent.com/9027679/130296150-826081a6-a99c-4d6c-9085-b89c8b520da2.png)
) to export in bulk.
In some of my collections I have about 50 items with notes so I was hoping for a more efficient way of exporting en masse.

**Comment by argenos** [comment]
Not <kbd>Ctrl</kbd>, <kbd>Shift</kbd>! See the difference here: 

![Peek 2021-08-23 16-14](https://user-images.githubusercontent.com/5426039/130462825-1814b8f9-d846-4495-8066-da454d4c2b2e.gif)

I'll leave the issue open, though! It should be possible to add a way to do it when right-clicking on collections, I just can't say when I'll have some time to tackle it.

**Comment by cjpoor** [comment]
Ok. Thank you. I'll try that.

**Comment by cjpoor** [comment]
That looks good. Thank you!

**Comment by elviskahoro** [comment]
I think this issue can be closed

**Comment by brimwats** [comment]
yes
