### ISSUE TITLE
Export fails - Module `zotero/filePicker` is not found 

### ISSUE THREAD

**Issue by FamRau** [argenos/zotero-mdnotes#126]
**Describe the bug**
If I want to export an entry with MDNotes, nothing happens. 

**To Reproduce**
1. Go to 'Zotero Context Menu'
2. Click on 'MDNotes/Export to markdown OR Batch export to markdown OR Create MDnotes file'
3. See error in the debug log:
`(3) (+ 0003015): Error: Module `zotero / filePicker` is not found at chrome: //zotero/content/filePicker.js batchExportMenu @ chrome: //mdnotes/content/mdnotes.js: 1054: 26 `

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Zotero version: [v5.97 beta 39]
 - Mdnotes version: [v0.1.3]
 - Zotfile version: [v5.0.16]
 - BetterBibtex version: [v5.4.28]

**Additional context**
Same failure with Mdnotes 0.2.0-alpha

**Comment by argenos** [comment]
Hi @FamRau, unfortunately I haven't had time to upgrade to the beta, so this is not yet supported.

**Comment by jmhammond** [comment]
@argenos  update Zotero beta again. I think it might be fixed now. 🤞 [This commit](https://github.com/zotero/zotero/commit/ba7d0a18aa556b74b92d845289cbc6aba12ff144) added in the missing `saveSelection()` function that was recently removed; that was preventing my mdnotes (and zotfile) from yesterday.

**Comment by enricllagostera** [comment]
I can confirm that I'm having the same issue of failing exports in Zotero (5.0.97-beta.41+aa7f5289a) with Mdnotes 0.13. The error message on the Output Log is the same as in @FamRau's report.

**Comment by argenos** [comment]
As I mentioned above, there is no ETA for the fix. I'll most likely be 
waiting until the new viewer adds more options for highlighting or comes 
out of beta. See discussion #77

**Comment by dstillman** [comment]
We've [temporarily restored](https://github.com/zotero/zotero/commit/4cfa230508e05a241cfeda05f68d137b8b8d3031) the `zotero/filePicker` path in the latest beta.

**Comment by argenos** [comment]
Thanks, @dstillman, what is the recommended way to use the `filePicker` for the beta?

**Comment by dstillman** [comment]
See https://github.com/zotero/zotero/commit/af597d943bd1128e741d530ef4b1d0ebaf8d3b25 — just need to add `modules` to the path.

**Comment by argenos** [comment]
Should have been fixed in the latest release.
