### ISSUE TITLE
Not saving files links

### ISSUE THREAD

**Issue by eisaias2000** [argenos/zotero-mdnotes#127]
**Describe the bug**
When I export the note to markdown, the text is exported properly, but the links to the Zotero item and pdf page are not.

**To Reproduce**
1. Go to a Zotero note file
2. Right click on the note
3. Click on MdNotes
4. Click on "Export to markdown"
5. Select the location to the exported md file
6. Open the exported md file

**Expected behavior**
I expected that md file contains the text of the note with the links to the Zotero item

**Screenshots**
<img width="1004" alt="Captura de Tela 2021-08-28 às 18 06 52" src="https://user-images.githubusercontent.com/51765377/131231051-03050691-9155-4f47-a3dc-2e6ecee633d0.png">
<img width="590" alt="Captura de Tela 2021-08-28 às 18 07 37" src="https://user-images.githubusercontent.com/51765377/131231055-dfea1f6d-dec9-43d8-bfe8-5883eb96fdb2.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Zotero version: 5.96.3
 - Mdnotes version: 0.1.3
 - Zotfile version: 5.0.16
 - BetterBibtex version: 5.4.28

**Additional context**

**Comment by huddao** [comment]
I have the same problem, it occur when using underline highlighting.
