### ISSUE TITLE
mdnotes does not work in Zotero beta?

### ISSUE THREAD

**Issue by sahmoli** [argenos/zotero-mdnotes#130]
The zotero-mdnotes does not work, I could not export markdown in Zotero anymore. 
Is that because I am using Zotero beta?

**Comment by cjpoor** [comment]
@argenos See this discussion regarding changes in Zotero that require updates to plugins:
https://forums.zotero.org/discussion/91449/add-ons-broken-in-the-latest-beta-version-bbt-zutilo-etc

**Comment by argenos** [comment]
Please refer to the discussion in #77 and #126 and #133
