### ISSUE TITLE
Include parent collections in topics

### ISSUE THREAD

**Issue by linxule** [argenos/zotero-mdnotes#14]
It seems that parent collection(s) is not included unless one item is manually added to the parent collection(s). Would it be possible to include the parent collection(s) as an option? Thank you!

**Comment by brimwats** [comment]
Recommend this be optional (which you have probably already thought of @argenos)—this might mess up some folks workflow when they actually don't want things in parent folders or categories too.

**Comment by brimwats** [comment]
(I, for one, love the idea and it would save the the time of manually doing it)
