### ISSUE TITLE
Export note with its "related" links and tags 

### ISSUE THREAD

**Issue by AntonioBlaGra** [argenos/zotero-mdnotes#15]
There is valuable information collected in the "tags" and "related" fields that it is lost when converted to md. It would be amazing to be able to keep it.

A decision has to be made on how to keep it: my understanding is that different md editors manage internal links differently. I guess the more standard the better.

**Comment by argenos** [comment]
@AntonioBlaGra I added something for this in #35. I'll probably release the new version on the weekend, but there is a `xpi` in the linked PR in case you want to test beforehand.
