### ISSUE TITLE
Mdnotes for Zotero is incompatible with Zotero 6.0-beta.1+c6d03753f

### ISSUE THREAD

**Issue by yourlulu1997** [argenos/zotero-mdnotes#152]
**Describe the bug**
The plugin is not compatible with Zotero.

**Expected behavior**
It can not be used anymore.

**Screenshots**
<img width="691" alt="截屏2022-02-10 下午1 24 56" src="https://user-images.githubusercontent.com/62187586/153343015-2c6f0d01-64f0-4951-80ef-05807faceb0c.png">

**Desktop (please complete the following information):**
 - MacOS Big Sur
 - Zotero version: 6.0-beta.1+c6d03753f
 - Mdnotes version: v0.1.3
 - Zotfile version: [v5.0.16]
 - BetterBibtex version: v6.2.4

**Comment by argenos** [comment]
Please see #133
