### ISSUE TITLE
Doesn't work with the new Zotero (6.0-beta.5+8b7afcf24)

### ISSUE THREAD

**Issue by Lemonnonioiiii** [argenos/zotero-mdnotes#158]
<img width="709" alt="截圖 2022-03-06 17 37 43" src="https://user-images.githubusercontent.com/57816341/156932639-95115cc3-7e3a-48a1-adcc-0601c5ed004f.png">

**Comment by jakepog** [comment]
Same issue as #133.

**Comment by iplane787** [comment]
me, too

**Comment by argenos** [comment]
Please see the pinned issue  (#133)
