### ISSUE TITLE
Is there a way to set the prefix?

### ISSUE THREAD

**Issue by rlam3** [argenos/zotero-mdnotes#16]
Is there a way to set the prefix of the note being exported? 

In addition to the `-zotero` I'd like to use a prefix before the citation key. Thank you!

**Comment by argenos** [comment]
@rlam3 I added something for this in #35, I'll probably release the new version on the weekend, but I already uploaded an `xpi` in the linked PR in case you want to test beforehand.

**Comment by rlam3** [comment]
@argenos Thanks! Looking forward to the release. Is there a specific way to update the package? Do I just reinstall the release or is there a way to patch it?

**Comment by argenos** [comment]
Hi @rlam3! I just released v0.1.0, so the usual update should work. Alternatively you can get the `xpi` from the [releases](https://github.com/argenos/zotero-mdnotes/releases).
