### ISSUE TITLE
Not working with Zotero 6.0.3

### ISSUE THREAD

**Issue by sunyuqian1997** [argenos/zotero-mdnotes#167]
<img width="988" alt="image" src="https://user-images.githubusercontent.com/44117903/160306277-e7b9db72-17c9-4b63-ab38-38ed9b1a4f03.png">

 - OS: big sure 11.2.3
 - Zotero version: [v6.0.3]
 - Mdnotes version: [0.1.3]
 - Zotfile version: [v5.1.1]
 - BetterBibtex version: [v6.2.14]

**Comment by milld10** [comment]
Exporting notes to Markdown is now included in Zotero 6.
https://www.zotero.org/support/changelog

**Comment by argenos** [comment]
Please see the pinned issue #133
