### ISSUE TITLE
List markers are mixed in export

### ISSUE THREAD

**Issue by Jmuccigr** [argenos/zotero-mdnotes#169]
**Describe the bug**

In an exported list of tags, the first item has `*` as a marker and the rest have `-`. For example:

```
* #building-cost
- #Building-materials
- #economy,-ancient
```

**To Reproduce**

Exporting with "Create full export note" I have this as my template:

```
@%(citekey)

{{title}}

## Metadata

{{author}}
{{date}}
{{related}}
 
## Notes



## Topics

{{tags}}
```

Additionally the three items under "Metadata" result in a list with asterisks:

```
* Authors: [[John Salmon]]
* Date: [[2002]]
* Related: [[Mattingly2002]], [[Davies2002]]
```

**Expected behavior**

All the list markers should be the same (preferably a hyphen). This was how it used to work.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Zotero version: 6.0.4
 - Mdnotes version: 0.1.3
 - Zotfile version: 5.1.1
 - BetterBibtex version: 6.4.0

**Comment by argenos** [comment]
Likely a result of how you have configured the formatting of the `{{bullet}}` or any custom placeholders. See [[Custom Formatting | Zotero-mdnotes](https://argentinaos.com/zotero-mdnotes/docs/next/advanced/formatting)](https://argentinaos.com/zotero-mdnotes/docs/next/advanced/formatting) for more info.

**Comment by Jmuccigr** [comment]
> Likely a result of how you have configured the formatting of the `{{bullet}}` or any custom placeholders. See [Custom Formatting | Zotero-mdnotes](https://argentinaos.com/zotero-mdnotes/docs/next/advanced/formatting) for more info.

Thanks. It was the bullet, which in fact I didn't have it configured at all. I changed it to `-` from the default `*` and that brought back the old behavior.
