### ISSUE TITLE
citations to annotations are not linked

### ISSUE THREAD

**Issue by wjfeeney** [argenos/zotero-mdnotes#170]
MacOS 12.3.1
Zotero 6.0.4
Mdnotes for Zotero 0.1.3
Zotfile 5.1.1
BBT 6.4.0

Mdnotes > Export to markdown / Create full export note

The citations to annotations are included in the exported file, e.g., (Regan, 2007, p. 318), but the citation is NOT linked (i.e., the `zotero://open-pdf`) to the cited page.

**Comment by appw-cn** [comment]
I have the same problem. appreciate if this could be sloved.

**Comment by appw-cn** [comment]
> Are these annotations extracted with Zotfile? Mdnotes just exports the markdown from the yellow Zotero notes, so your method of extracting the annotations might be at fault for the missing link.

The annotations are extracted with built-in "Add Notes from annotations" and "mdnotes - create full export notes".
In zotero, when I click "show on page", it will jump to the PDF page. But after exporting, I can no longer jump to the PDF page with a click. Is it possible add a PDF link at the end of the notes? I mean something like this:
`  ([pdf](zotero://open-pdf/library/items/R45H4I7M?page=1&annotation=GLKTL48D))`

Thanks

**Comment by argenos** [comment]
You should try to modify how Zotero makes those yellow notes from your annotations in that case (https://www.zotero.org/support/note_templates). Closing this since it's not an mdnotes issue per se.
