### ISSUE TITLE
'add-ons installation failed' for Zotero 6.0.4

### ISSUE THREAD

**Issue by MengjieSHI** [argenos/zotero-mdnotes#175]
Hi,
Just updated Zotero to the latest version (6.0.4) and try to install 'mdnotes'. it says 'The add-on "Mdnotes for Zotero" could not be installed. It may be incompatible with this version of Zotero'.
BTW, I have installed ZotFile and Better BibTex.

Does anyone have the same issue?

**Comment by 1qzhworld** [comment]
You should try "v.0.2.0-alpha5 - Zotero 6 compatibility". It works in Zotero 6+.
> https://github.com/argenos/zotero-mdnotes/releases/tag/0.2.0-alpha5

**Comment by MengjieSHI** [comment]
> You should try "v.0.2.0-alpha5 - Zotero 6 compatibility". It works in Zotero 6+.
> 
> > https://github.com/argenos/zotero-mdnotes/releases/tag/0.2.0-alpha5

ah thanks!  Quite stupid, I missed the latest release.
