### ISSUE TITLE
zotero 6.0.5 refused to load mdnotes.

### ISSUE THREAD

**Issue by jbisgrove** [argenos/zotero-mdnotes#178]
**Describe the bug**
zotero 6.0.5 refused to load mdnotes.

**To Reproduce**
1. download mdnotes
2. zotero->tools->addons
3. install addon from file
4. select mdnotes file

**Expected behavior**
expect addon to be loaded into zotero
**Screenshots**
![image](https://user-images.githubusercontent.com/2701527/164951725-f0ac8b4f-9494-40f7-9d99-a8d838835fa8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Zotero version: [6.0.5]
 - Mdnotes version: [v0.1.3]
 - Zotfile version: [v5.1.1]
 - BetterBibtex version: [v6.5.2]

**Additional context**

**Comment by argenos** [comment]
Please install the alpha 5 from the releases.
