### ISSUE TITLE
Update stuck in v0.0.6

### ISSUE THREAD

**Issue by trungng2006** [argenos/zotero-mdnotes#18]
Even when i installed the 0.0.7 from this website, Zotero will auto "update" it to 0.0.6.
And it will keep updating 0.0.6 everytime i click update addon. (0.0.6 -> 0.0.6)

**Comment by argenos** [comment]
Hi @trungng2006 , could you tell me what version of Zotero and what OS are you using? If you could add a screenshot that would be great.

**Comment by trungng2006** [comment]
Dear Argenos,
Thank you for the great plugin.
I use Zotero 5.0.89. and win10
https://ibb.co/Fq9dM63

**Comment by argenos** [comment]
After you restart Zotero, is the version still 0.6.0? 

If that doesn’t work, could you remove the plugin and install from scratch? You might lose your settings after doing so.

**Comment by trungng2006** [comment]
After you restart Zotero, is the version still 0.6.0? => yes.

I have just removed, restart, reinstall 0.0.7 xpi, then restart again.
the add on show 0.0.6. and when i click update, it update again, to 0.0.6 and prompt restart again.

**Comment by IpeTek** [comment]
I face the exact same problem. Plus export to a note fails intermittently without any obvious reason.

**Comment by argenos** [comment]
This is a known bug, I'm hoping to be able to push a fix in the coming week. In the meantime, you can install 0.7.0 by downloading the following file and changing the extension from `zip` to `xpi`:

[mdnotes-0.0.7-fx.zip](https://github.com/argenos/zotero-mdnotes/files/5471533/mdnotes-0.0.7-fx.zip)

**Comment by argenos** [comment]
Starting on v0.1.0 updates shouldn't be stuck, so I'll close this. Please let me know if that's not the case!
