### ISSUE TITLE
can not find the corresponding options in "advanced configuration - config editor"

### ISSUE THREAD

**Issue by Xieleilab** [argenos/zotero-mdnotes#186]
when using the plugin"mdnotes for zotero", if i write"{{publicationTitle}}" in it, the exported markdown will automatically replace it with the reference's pulication title name, however, if i want to Modify the format of the exported content corresponding to {{publication}}，i can not find the corresponding options in "advanced configuration - config editor"

**Comment by argenos** [comment]
You can add it as described in the [documentation](https://argentinaos.com/zotero-mdnotes/docs/next/advanced/formatting)
