### ISSUE TITLE
Batch export naming behaviour

### ISSUE THREAD

**Issue by ScriBanana** [argenos/zotero-mdnotes#19]
Hi,

I'm having an odd issue, there is a high chance it is a bug :
With

- _Use the item's citekey as title?_ unchecked and
- _Single file_ organization

In _Internal Links_, switching from _[[Wiki style]]_ to any of the two other styles weirdly affects the naming of the file : caps are off and there are hyphens between words.

Example :
> **Wiki :** An Automatic Monitoring System for High-Frequency Measuring and Real-Time Management of Cyanobacterial Blooms in Urban Water Bodies.md
> **No link or markdown :** an-automatic-monitoring-system-for-high-frequency-measuring-and-real-time-management-of-cyanobacterial-blooms-in-urban-water-bodies.md

Thanks for your work, by the way!

**Comment by argenos** [comment]
Not really a bug, but rather a hardcoded assumption. I assumed people who are using markdown links needed hyphens between words for links to be clickable (e.g. in GitHub pages). I made them all lowercase based on *my* preference at the time. I have something in progress that could help with this, but just to make sure I test for the format you want, could you mention how that link would look like?

**Comment by ScribanA** [comment]
I don't really have a specific request. I was messing around when I found what I considered as a strange behaviour and potential bug.
I use the Better BibTeX citekey and view the md file in Obsidian (which is what you do as well, if I'm not mistaken), so I can't give you an example of process in which this would cause an issue.

**Comment by argenos** [comment]
Fixed in #35
