### ISSUE TITLE
http to doi

### ISSUE THREAD

**Issue by ScriBanana** [argenos/zotero-mdnotes#20]
Would it be possible to (have an option to) add the _http_ in the doi links?

> Current : `*DOI: [10.0000/pr6000001](10.00000/pr6000001)`
> Suggestion : `*DOI: [10.0000/pr6000001](https://doi.org/10.00000/pr6000001)`

**Comment by argenos** [comment]
This is a bug that will be fixed on the next release. Thanks for reporting it!

**Comment by ScribanA** [comment]
Damn, my enhancement suggestion becomes a bug and my bug report becomes an enhancement suggestion! :D

**Comment by argenos** [comment]
I have an `xpi` that fixes this in #35 in case you want to test this before the release. The update introduces other changes, just in case you want to wait for the official release.
