### ISSUE TITLE
C9TAWKMI-apse

### ISSUE THREAD

**Issue by chloeskafte** [argenos/zotero-mdnotes#203]
**Describe the bug**
The 'Create full export note' function is no longer working.

**To Reproduce**
1. Right click on the citation entry after creating an Annotation Note 
2. Select Mdnotes > Create full export note
3. Save into a folder in the Obsidian Vault
4. Once folder is selected the folder it never appears in the Obsidian Vault
5. This is the error... 
6. (4)(+0000018): Committed DB transaction lu6r4JCt

(3)(+0000555): Getting contents of C:\Users\user\Documents\Obsidian Vault\Mdnotes Default Template.md

(3)(+0000007): SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 117 of the JSON data getFormattingSettings@chrome://mdnotes/content/mdnotes.js:714:36 format_placeholders@chrome://mdnotes/content/mdnotes.js:602:20 getMDNoteFileContents@chrome://mdnotes/content/mdnotes.js:460:31

**Expected behavior**
A full note including metadata and annotations would be created in the Obsidian Vault.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Zotero version: 6.0.18
 - Mdnotes version: 0.1.3
 - Zotfile version: 5.1.2
 - BetterBibtex version: 6.7.43

**Comment by perryg45** [comment]
I have the exact problem. It worked a few days ago, and now not working.  Windows 10, Mdnotes 0.2.3, Zotero 6.0.19

**Comment by john-james-ai** [comment]
I have the same issue with the exception of not getting an error message. I would also add that the filepicker seems to ignore my export directory set in mdnotes preferences.

**My mdnotes preferences:**
- Use items' Citekey as title: UNCHECKED
- Show Standalone Note Menu: CHECKED
- File Organization: Split Files
- Internal Links: Wiki
- Export Directory chosen 

**Desktop**:
- OS: Windows 10
- Zotero version: 6.0.20
- Mdnotes version: 0.1.3
- Zotfile version: 5.1.2
- BetterBibtex version: 6.7.53

**Comment by john-james-ai** [comment]
The following worked for me:
1. Run check updates on Zotero via the Help menu.
2. Install the latest version of Obsidian
3. Remove zotero-mdnotes addin from Zotero
4. Reinstall zotero-mdnotes following the instructions [here.](https://github.com/argenos/zotero-mdnotes). 
5. Restart Zotero

Upon restart, right-click a document and select Mdnotes>Create Mdnotes File.  Select the download location and viola!
Good luck!
