### ISSUE TITLE
Multi Word Keywords in Zotero get split as TAG's (#)

### ISSUE THREAD

**Issue by StoltHD** [argenos/zotero-mdnotes#21]
I have a lot of Multi Word Keywords in Zotero (Names, Occupations and so on).

But when exporting to MD and open in i.e. Obsidian, only the first Word or Character are converted to a TAG when there are spaces in the Zotero Keyword.

Would it be possible to automatically eiter replace all spaces in a Keyword with i.e. a "_" underscore, or to get Multi Word TAG in the MD files?

This happens when I try to use hashtag.

A good additional alternative formulti word keywords there all words are multi character (i.e. more than 3 char) would be to automatically create sub-tags (i.e. CamelBack or Hyphen based)...

As it is now, I got a lot of single Character TAG's in i.e. Obsidian or Zettlr.

I use multi word keyword to tag both Workflow based notations and Content in Zotero, and it would be great if it was possible to get this reflected in the MD files...

**Comment by argenos** [comment]
I already have something in progress for this, will be available in the next release (sorry it's taking a while, not a lot of free time at the moment)

**Comment by StoltHD** [comment]
Thanks, that's great... no rush for my part, I'm still in testing period...

It would be great if it was possible with multi word with space as delimiter, but I saw after i wrote this issue that neither Zettlr nor Obsidian support it as TAG, only as Keywords in the YAML Frontmatter, and that is not used the same way as TAGs at the moment...

**Comment by StoltHD** [comment]
Just want to add, that you have done a great job with this so far...

**Comment by argenos** [comment]
This should be possible to set up with custom formatting starting in v0.1.0 in case your editor supports it.
