### ISSUE TITLE
MdNotes not generating anything (on Macbook 2023)

### ISSUE THREAD

**Issue by paulinvienna** [argenos/zotero-mdnotes#215]
**Describe the bug**
Mdnotes does not create/export any markdown file: whatever I select (create markdown file, export to markdown, batch export to markdown), it brings up the folder where the md file should be saved, but no note gets generated. 

**To Reproduce**
1. Go to the note/parent file
2. Right click and select Mdnotes
3. Select "batch export to markdown"
4. Select target folder and click "open"
5. No note is generated

**Expected behavior**
Previously, this created a note in the target folder, which I could see both within Zotero (under the parent file), in finder (I'm working with Mac) and in Obsidian.

**Screenshots**
Screenshots don't work as it is the absence of action that is the problem.

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura 13.2.1
 - Zotero version: [v6.0.23]
 - Mdnotes version: [v0.2.3]
 - Zotfile version: [v5.1.2]
 - BetterBibtex version: [v6.7.67]

**Additional context**
This was not a problem when I was using my previous MacBook (Intel) - but seems to be an issue since installing it on my new MacBook (Apple M2)

**Comment by kun-wang** [comment]
I meet the same problem. The "Debug Output Logging" information from Zotero/Help/ is as follows:

TypeError: fileName is undefined getValidFileName@chrome://zotero/content/xpcom/file.js:1251:5 getNCFileName@chrome://mdnotes/content/mdnotes.js:414:14 getMDNoteFileName@chrome://mdnotes/content/mdnotes.js:421:10 getItemMetadata@chrome://mdnotes/content/mdnotes.js:238:30 getRegularItemContents@chrome://mdnotes/content/mdnotes.js:945:22 exportToMarkdownMenu@chrome://mdnotes/content/mdnotes.js:1037:26

**Comment by kun-wang** [comment]
> I meet the same problem. The "Debug Output Logging" information from Zotero/Help/ is as follows:
> 
> ```
> TypeError: fileName is undefined getValidFileName@chrome://zotero/content/xpcom/file.js:1251:5 getNCFileName@chrome://mdnotes/content/mdnotes.js:414:14 getMDNoteFileName@chrome://mdnotes/content/mdnotes.js:421:10 getItemMetadata@chrome://mdnotes/content/mdnotes.js:238:30 getRegularItemContents@chrome://mdnotes/content/mdnotes.js:945:22 exportToMarkdownMenu@chrome://mdnotes/content/mdnotes.js:1037:26
> ```

As mentioned in issue #224, my problem dues to the BetterBibtex update on October 24th.

I fixed the problem by rolling back the version of BetterBibtex.
