### ISSUE TITLE
Cannot export a note

### ISSUE THREAD

**Issue by walkinverse** [argenos/zotero-mdnotes#218]
With the current version, you cannot export a single note.  You can export the cite, but not the note.  The previous version worked fine.

0.1.3 can export a note as a markdown file. The current version cannot, it's broken.

The last version to work is 0.2.1.  All other current will not export markdown notes. Create mdNotes File also does not work when you select a note in any version except for 0.1.3.  

Zotero version 6.0.27 on Mac.

Let me know if you need a screencast to show.

**Comment by Pisceanjc** [comment]
I have same issue. Can't export not to Obsidian. Please let e know if their any solution.

**Comment by hajdukste** [comment]
See my reply in #149.
