### ISSUE TITLE
Collections and sub Collections as folder-structure

### ISSUE THREAD

**Issue by StoltHD** [argenos/zotero-mdnotes#22]
Is it somehow possible to export the Collection structure as a folder structure?
Or can you add this function?

I have seen someone asking for all Parent Collections (i.e. the complete structure) as "Topics"
If you are to implement this, would it be possible for you to add a feature to choose either "Topic" or "Folder Structure" or both?

Great tool... I have looked for something like this for a long time, so thanks...

**Comment by argenos** [comment]
Could you clarify a little what you mean by folder structure? The parent collections as topics would just use comma-separated links for each parent collection. An example of how the export would look would be helpful!

**Comment by StoltHD** [comment]
It's easy, the same structure as folders on disk as the collections in Zotero...
so if you have a collection structure like
Collection 1
- Sub-Col 1
-- Sub-Sub-Col1
Collection 2

You get the same folder structure in the root folder that you choose (i.e. the obsidian vault)

This will be in addition do the "Topics", or a YAML Frontmatter ...
