### ISSUE TITLE
Any plans on zotero 7 support?

### ISSUE THREAD

**Issue by Leonezz** [argenos/zotero-mdnotes#220]
**Is your feature request related to a problem? Please describe.**

Clearly this plugin does not work with zotero 7, which is a major update of zotero with massive performance improvement.

**Describe the solution you'd like**

Hopefully this plugin could be updated such that we could use it with zotero 7 soon.

**Additional context**

Thanks for your work and this plugin provides useful functionallity for work process in terms of research, hope we could use it in zotero 7 soon!

**Comment by argenos** [comment]
No, I have no plans to update mdnotes to Zotero 7
