### ISSUE TITLE
(Macbook related) While export markdown file or create mdnotes file, mdnotes can't create the correct paper name but "undefined-zotero.md"

### ISSUE THREAD

**Issue by stevenstg** [argenos/zotero-mdnotes#223]
**Describe the bug**
While export markdown file or create mdnotes file, mdnotes can't create the correct paper name but "undefined-zotero.md". 
I'm using the same template on my win and mac, but it works well on win and automatically generate file name while create mdnotes file. However, while on my mac, the file name appears to be "undefined" and I need to text the file name by my own. 

**To Reproduce**
 1. Right click the paper.
 2. Go to "Mdnotes->Create Mdnotes file OR export to markdown file"
 3. The file name will be "Undefined-zotero.md"

**Expected behavior**
Hopefully the issue will be resolved on macbook.

**Screenshots**
![image](https://github.com/argenos/zotero-mdnotes/assets/92260709/51ec92be-484b-42a2-92c1-4b93f3b2b33f)
The right md file is by windows, the undefined is by macbook.
![image](https://github.com/argenos/zotero-mdnotes/assets/92260709/6782a9e3-a328-4f92-9cef-b1ff87533357)
![image](https://github.com/argenos/zotero-mdnotes/assets/92260709/69e284a0-8bc4-4390-9187-78e5134404cb)

**Desktop (please complete the following information):**
 - OS: MacOS ventura 13.5.2
 - Zotero version: v6.0.27
 - Mdnotes version: v0.2.3

**Comment by sfsdfc** [comment]
I've encountered the same bug as well on my Ubuntu 22.04.3 operating system.
