### ISSUE TITLE
Mdnotes creation failed

### ISSUE THREAD

**Issue by TKBeckum** [argenos/zotero-mdnotes#226]
**Describe the bug**
Asfter (automatic) update to Zotero 6.0.29 I cannot create Mdnotes file. Nothing happens, not even an error message. I removed and reinstalled the latest xpi's for Mdnotes, Zotfile and Better Bibtex, but that didn't help.

**To Reproduce**
1. Go to an item in Zotero
2. Right-Click on the item
3. Scroll down to Mdnotes, click and choose 'Create Mdnotes file'
4. nothing happens

**Expected behavior**
Creation of a Mdnotes file 

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: MacOS Moneterey 12.7.1
 - Zotero version: 6.0.29
 - Mdnotes version: 5.1.2
 - Zotfile version: [v5.0.16]
 - BetterBibtex version: 6.7.135

**Additional context**
Untill today Mdnotes were created without any problem

**Comment by TKBeckum** [comment]
Thanks, that helped!

**Comment by ccritesaccordia** [comment]
Also work for me: "export the mdnotes successfully by unticking the box "Use the item's citekey as title" (src:  [Issues about exporting markdown file by "mdnotes" - Zotero Forums](https://forums.zotero.org/discussion/comment/446847/#Comment_446847))

**Comment by danielyang1009** [comment]
same problem here, have to uncheck using citekey as title, and the manually fix file name

**Comment by jatolispark** [comment]
i have the same question, it can successfully open the export loacation selecting window, but it could not build a file in the selected folder. can u help me?
