### ISSUE TITLE
The BBT gets the citation key, but there is no file export.

### ISSUE THREAD

**Issue by jatolispark** [argenos/zotero-mdnotes#229]
# Version
mdnotes v0.2.3 (fiexed)
Better BibTeX v6.7.163
Zotero v6.0.33
MacOS 14.1.1 (23B81) Apple M2

# how did i fixed the mdnotes add-on

change this funciton

```javascript

function getCiteKey(item) {
  if (typeof Zotero.BetterBibTeX === "object" && Zotero.BetterBibTeX !== null) {
    var bbtItem = Zotero.BetterBibTeX.KeyManager.get(item.getField("id"));
    return bbtItem.citekey;
  }

 ```

it successfully show me the window to choose where I can export the mdfile, but it still didn't work to export a markdown file in the target folder.

# the progress of the question happened

1. i create the mdfile
<img width="221" alt="image" src="https://github.com/argenos/zotero-mdnotes/assets/80537007/a2674417-80dc-4a46-9703-a19362c4486c">

2. I choose the folder to export
<img width="941" alt="image" src="https://github.com/argenos/zotero-mdnotes/assets/80537007/c5263862-2b24-47e3-a61c-b6f10772f616">

3. but it didn't appear in the selected folder.
<img width="1398" alt="image" src="https://github.com/argenos/zotero-mdnotes/assets/80537007/2e7c9ad3-76d8-416e-8afc-8392497dd9e8">

if you can help me to solve the problem, i will be too much grateful! the add-on has accelerated my workflow a lot! but today it suddenly didn't work.

**Comment by DivingWhale** [comment]
Here's a solution: #225 by RobaaaT. But you need to repack and reinstall yourself.
