### ISSUE TITLE
Underlined texts are as the heading

### ISSUE THREAD

**Issue by TomBener** [argenos/zotero-mdnotes#24]
The underlined texts in PDF which are annotated by PDF Expert are always extracted as Heading 4.

I'd like to make the underlined texts normal body like the highlighted texts. Please fix it. Thank you!

Screenshot are as follows.

<img width="992" alt="截屏2020-10-21 16 01 12" src="https://user-images.githubusercontent.com/49151155/96690849-c67d2d00-13b6-11eb-9861-d52302acbea9.png">

<img width="741" alt="截屏2020-10-21 16 01 32" src="https://user-images.githubusercontent.com/49151155/96690868-cbda7780-13b6-11eb-85d4-f9120acf7708.png">

**Comment by argenos** [comment]
This is intentional. The upcoming release will expose the formatting so you can customize it to your liking.

**Comment by TomBener** [comment]
Thanks for your reply. Looking forward the upcoming release.

**Comment by argenos** [comment]
Hi @TomBener #35 introduces custom formatting, you should use the hidden preference `extensions.mdnotes.html_to_md`. That is the dictionary of how the HTML elements are translated into markdown.

**Comment by argenos** [comment]
Forgot to say that I'll probably release on the weekend, but there is an `xpi` in the linked PR.
