### ISSUE TITLE
Headings in notes not formatted

### ISSUE THREAD

**Issue by n8craig** [argenos/zotero-mdnotes#25]
Thank you for this fantastic tool, I just started using it and think its going to be fantastic!

I notice that the [export notes to markdown](https://github.com/argenos/zotero-mdnotes#export-zotero-notes-to-markdown) readme shows manually created notes and zotfile annotations carrying formatting over from zotero. When I export my own notes, which often have chapter of section headings those headings aren't reflected in the output markdown note. Perhaps I've failed to properly adjust a setting, but if not I wanted to bring this to your attention. Thank you again for your efforts on this very awesome tool.

Win 10
Zotero 5.0.92
Zotero-mdnotes 0.0.7

**Comment by argenos** [comment]
It's not there yet, but the next release should expose a way to customize the formatting from Zotero notes (using html) to markdown, so you can add how to format the headers too!

**Comment by argenos** [comment]
Hi @n8craig, I added support for custom formatting in #35. You should use the hidden preference `extensions.mdnotes.html_to_md`. You can add the HTML tags that are used for those headings to that dictionary, which is what mdnotes uses to translate them into markdown. If I were to guess, adding something like `"<h2>": "## "` should do the trick (I haven't tested myself yet).

**Comment by n8craig** [comment]
Exciting to see updates coming. Thank you so much for all your hard work on this really interesting and useful tool. Unfortunately, exported notes do not seem to be picking up formatting. None of the heading levels in Zotero are translated into the MD notes. Except for the first line of text, all heading items are plain text. _Italics_ and **bold** are both working. Underline is not nor is superscript. I believe the latter two are not stock markdown.

Win 10
Zotero 5.0.93
Zotero-mdnotes v0.1.2

**Comment by argenos** [comment]
Could you share what you have in `extensions.mdnotes.html_to_md`?

**Comment by argenos** [comment]
Also let me know if you have changed Zotfile's formatting settings.

**Comment by n8craig** [comment]
1. extensions.mdnotes.html_to_md;{"<p>": "", "</p>": "", "<strong>": "**", "</strong>": "**","<b>": "**","</b>": "**","<u>": "#### ","</u>": "","<em>": "*","</em>": "*", "<blockquote>": "> ", "</blockquote>": "", "<br><br>": "\n\n"}

2. I'm not sure about changing Zotfile's formatting settings. I don't think so because I'm not sure how to.

**Comment by argenos** [comment]
You need to add to that dictionary how the HTML tags should be translated, e.g by adding `"<h2>": "## "` to the list (don't forget to separate it from the other formatting rules with a comma.
