### ISSUE TITLE
Bibliography export

### ISSUE THREAD

**Issue by elliotl1l** [argenos/zotero-mdnotes#26]
Now that the cite key is exported, it would be great that the bibliography can be exported in the default format at the same time, please consider adding it, thanks a lot!

**Comment by argenos** [comment]
@eddie506 what do you mean by "exporting the bibliography"?

**Comment by eddie506** [comment]
For example:
Cite key: Scheffer and Berkovic 1997
Bibliography (or should I say citation?): Scheffer, I. E., and S. F. Berkovic. 1997. “Generalized Epilepsy with Febrile Seizures plus. A Genetic Disorder with Heterogeneous Clinical Phenotypes.” Brain: A Journal of Neurology 120 ( Pt 3): 479–90.
I was trying to distinguish it from the cite key, maybe I got it wrong, sorry to cause misunderstanding.

**Comment by eddie506** [comment]
For example:
Cite key: Scheffer and Berkovic 1997
Bibliography (or should I say citation?): Scheffer, I. E., and S. F. Berkovic. 1997. “Generalized Epilepsy with Febrile Seizures plus. A Genetic Disorder with Heterogeneous Clinical Phenotypes.” Brain: A Journal of Neurology 120 ( Pt 3): 479–90.
I was trying to distinguish it from the cite key, maybe I got it wrong, sorry for causing the misunderstanding.

**Comment by eddie506** [comment]
Cite key: Scheffer and Berkovic 1997
Bibliography (or should I say citation?): Scheffer, I. E., and S. F. Berkovic. 1997. “Generalized Epilepsy with Febrile Seizures plus. A Genetic Disorder with Heterogeneous Clinical Phenotypes.” Brain: A Journal of Neurology 120 ( Pt 3): 479–90.
I was trying to distinguish it from the cite key, maybe I got it wrong, sorry for causing the misunderstanding.
I mean I want to export the bibliography/citation with the cite key at the same time.

**Comment by argenos** [comment]
It might be possible through BetterBibtex, so I'll take a look when I have some time.
