### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by qq1307229333** [argenos/zotero-mdnotes#29]
I have created the extracted annatations from PDF file which was mark lots of notes. However, when I selected the note file created by zotfile, then select batch export to markdown, and I choose the folder. It doesn't creat any file in this folder. Why would this thing happen?  
Thank you in advance.

![image](https://user-images.githubusercontent.com/29172075/97794737-a2341280-1c38-11eb-9094-79bd898b4c53.png)
![image](https://user-images.githubusercontent.com/29172075/97794772-efb07f80-1c38-11eb-8245-a47494e66afd.png)

**Comment by argenos** [comment]
Hi @qq1307229333, the menus are unfortunately not context-aware. You have to select the right item for that to work. Check out the cheatsheet at the top of the readme: https://github.com/argenos/zotero-mdnotes#features
