### ISSUE TITLE
The link to the physical pdf has the "wrong" path 

### ISSUE THREAD

**Issue by vasko-deb** [argenos/zotero-mdnotes#30]
When I create a metadata note using the "Create Zotero item metadata file" or "Create Notes file" buttons it does create the expected .md files at the folder location that I have specified. As you describe in the readme the link to the physical pdf attachment looks something like

* PDF Attachments: ``[Chen et al. - 2020 - Quantum Extremal Islands Made Easy, Part I Entang.pdf](zotero://open-pdf/library/items/V94J57B5)``

However, for me (Ubuntu 20.04) Zotero stores that pdf in the location /home/vasko/ownCloud/Zotero/storage/V94J57B5.

How can I change the path to the pdf file that gets populated in the markdown style link?

**Comment by argenos** [comment]
Hi @vasko-deb, I'm afraid my assumptions for this was that you were using Zotfile to keep your PDFs outside of Zotero's directory. I'm not sure if this is the reason why you're getting `zotero://` links. I'll have to check if Zotero can return a system path even if it's within its own directory.

**Comment by argenos** [comment]
@vasko-deb after re-reading, and going through the code, I'm afraid this was not really an option that I offered before. I added this to the upcoming release though, so it shoud be fixed by #35
