### ISSUE TITLE
Links in capital letters

### ISSUE THREAD

**Issue by ScriBanana** [argenos/zotero-mdnotes#31]
Hey,
I'm still enjoying using MdNotes so far, thank you!

I might be wrong, but it seems that link names from tags and collections (so I assume all of them) that are natively in full capital letters are transformed into a lower case word, with the exception of the first letter. Is there something I missed? It's quite annoying for acronyms.

Example :
- Zotero tag : `GITHUB`
- MD link : `[[Github]]`

Oh by the way, I think it is expected to be implemented in the next version, but could there be a possibility to choose, among the metadata to export, the format for each item (ex : collections as links, publication type as tags, author names as plain text, etc).

Thanks!

**Comment by argenos** [comment]
Sorry about the capitalization, this was a hack from when the plugin was meant for my personal use only. I'll see if I can add an option in the next release too.

And the custom format should indeed let you format if you want individual items as tags, links, or none (as well as your standard markdown formatting).

**Comment by ScriBanana** [comment]
Neat, thank you!

**Comment by argenos** [comment]
@ScriBanana #35 should also take care of this! You can check http://argentinaos.com/zotero-mdnotes/docs/formatting/#field-format for some documentation, let me know if that helps! The `xpi` is linked in the PR.
