### ISSUE TITLE
URL field not included in markdown file

### ISSUE THREAD

**Issue by ClonedOne** [argenos/zotero-mdnotes#34]
**Describe the bug**
The URL field is not included in the generated markdown file(s), despite being marked as "to export" in the settings page.

**To Reproduce**
Make sure "URLS" is selected in "to export".
Right click on zotero entry and select "batch export to markdown" 

**Expected behavior**
Markdown file containing the URL field.

**Screenshots**
![image](https://user-images.githubusercontent.com/6853743/98472347-695be680-21c0-11eb-943c-694304c8d710.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10 (Pop Os)
 - Zotero version: 5.0.93
 - Mdnotes version:v0.0.7
 - Zotfile version: v5.0.16
 - BetterBibtex version: v5.2.84

**Additional context**
N/A

Small extra question: Is there any way to remove the "Zotero Links" field from the generated markdown file?

Thank you for your great work!

**Comment by argenos** [comment]
I think this should be fixed in #35.

**Comment by argenos** [comment]
@ClonedOne just released v0.1.0, could you double-check and let me know if the fix works?

**Comment by ClonedOne** [comment]
@argenos not sure if the problem is fixed. Both the output of the plugin, and the options available, changed a lot, but I'm still not getting the content of `URL` in the batch export ouptu.

**Comment by argenos** [comment]
You're right! I'll push a fix later today.

**Comment by argenos** [comment]
Just to make sure the fix does solve it, could you try with this one?  [mdnotes-0.1.0-fx.zip](https://github.com/argenos/zotero-mdnotes/files/5547767/mdnotes-0.1.0-fx.zip)

**Comment by ClonedOne** [comment]
ok with that zip it seems to output the URL correctly

![image](https://user-images.githubusercontent.com/6853743/99420634-7321d000-28cb-11eb-8ab1-a76500d1744f.png)

**Comment by argenos** [comment]
Good! This should be then solved by v0.1.1 (and included in v0.1.2)

**Comment by ClonedOne** [comment]
By the way, with version 0.1 it always creates a new file in the Zotero folder when I use `batch export`. Is there a way to avoid that?

![image](https://user-images.githubusercontent.com/6853743/99420857-b9772f00-28cb-11eb-9f3b-eb21e1a89e43.png)

**Comment by argenos** [comment]
@ClonedOne yes, this was patched in 0.1.2, shouldn't happen automatically anymore!

**Comment by ClonedOne** [comment]
Thanks!
