### ISSUE TITLE
How to create .md note from Zotfile extracted annotations?

### ISSUE THREAD

**Issue by cobblepot1** [argenos/zotero-mdnotes#4]
Hi, this seems very useful to me but I can't figure out how to get Zotfile extracted annotations exported to a .md note as illustrated in the readme.md file. I selected the note and tried 'export' but no file was created. I also don't understand the difference between 'create notes file' and 'export Zotero note to markdown'. Is the item supposed to be highlighted or is a specific note supposed to be highlighted? Thanks for the help.

**Comment by argenos** [comment]
Could you check if you're using v0.0.1? I fixed the default path in Windows #3 for v0.0.2

In case you're running the latest version, could you check `Tools > Mdnotes preferences`, choose a path in your system and try again? 

The `Create notes file` menu creates a file for your own notes, i.e. it only uses the naming convention (e.g. `citekey.md`) to save a file that includes the item's title as an H1 header, a few links, and a H2 `Notes` header so you can write below. It should only work with Zotero items.

The `Export Zotero note to markdown` only works with Zotero notes (the ones with the little yellow icon), and that one will export the note contents and save them on a file using the naming convention, e.g. `citekey - <note title>.md`

**Comment by cobblepot1** [comment]
I do have v0.0.2. In the "Notes directory" in settings I have `D:\Downloads`.

When I highlight a Zotero note, and choose `Export zotero note to markdown` it asks me to select a folder (even though there is one in settings as above) but there is no filename shown. Is there supposed to be one? No file is created after I select 'ok'

**Comment by argenos** [comment]
For batch export there isn't any file name, since they are generated based on the naming convention. It should be creating the files after you click on `Open`.

Do you have better bibtex installed? Is the option to use the citekey selected?

**Comment by argenos** [comment]
[v0.0.3](https://github.com/argenos/zotero-mdnotes/releases/tag/0.0.3) should fix the problem of Zotfile's note titles in windows. Please note that to avoid having those characters in the file name, in the exported markdown file the date will be switched to `yyyy-mm-dd` format. Timezones might cause issues, but I hope I can make a PR to Zotfile to address this at the moment the annotations are extracted instead.
