### ISSUE TITLE
Color Dictionary

### ISSUE THREAD

**Issue by linxule** [argenos/zotero-mdnotes#41]
**Is your feature request related to a problem? Please describe.**

Referencing to the request for color dictionary at #8 

**Describe the solution you'd like**

To assign "names" to annotation colors and types (much like in Highlights App for Mac). It seems that the customization might be possible by manually changing the settings for Zotfile annotation extraction.

<img width="443" alt="20200910152747@2x" src="https://user-images.githubusercontent.com/43122877/92745354-3345e600-f37a-11ea-8987-a3496d6e3f04.png">
 
**Additional context**

**Comment by brimwats** [comment]
This! Or just "reading" that Zotfile has (Yellow) and then in the export replace the (Yellow) with (for example) "Important Point by Author" or tags as above
