### ISSUE TITLE
"Titles" for different item types

### ISSUE THREAD

**Issue by linxule** [argenos/zotero-mdnotes#42]
**Is your feature request related to a problem? Please describe.**

Currently, only ProceedingsTitle is available.

**Describe the solution you'd like**

Allow other types of titles to be used (e.g., publication, website, blog)
I have added other types of "titles" [in the preference file here](https://github.com/linxule/zotero-mdnotes/blob/master/defaults/preferences/mdnotes.js)

**Additional context**

To add these "title" types manually, here are the settings & values copied out of Zotero:

* publicationTitle
	* extensions.mdnotes.placeholder.publicationTitle;{"content":"{{bullet}} Publication: {{field_contents}}", "field_contents": "{{content}}", "link_style": "wiki"}
* programTitle
	* extensions.mdnotes.placeholder.programTitle;{"content":"{{bullet}} Program: {{field_contents}}", "field_contents": "{{content}}", "link_style": "wiki"}
* websiteTitle
	* extensions.mdnotes.placeholder.websiteTitle;{"content":"{{bullet}} Website: {{field_contents}}", "field_contents": "{{content}}", "link_style": "wiki"}
* blogTitle
	* extensions.mdnotes.placeholder.blogTitle;{"content":"{{bullet}} Blog: {{field_contents}}", "field_contents": "{{content}}", "link_style": "wiki"}
* bookTitle
	* extensions.mdnotes.placeholder.bookTitle;{"content":"{{bullet}} Book: {{field_contents}}", "field_contents": "{{content}}", "link_style": "wiki"}
* encyclopediaTitle
	* extensions.mdnotes.placeholder.encyclopediaTitle;{"content":"{{bullet}} Encyclopedia: {{field_contents}}", "field_contents": "{{content}}", "link_style": "wiki"}
* forumTitle
	* extensions.mdnotes.placeholder.forumTitle;{"content":"{{bullet}} Forum: {{field_contents}}", "field_contents": "{{content}}", "link_style": "wiki"}
* shortTitle
	* extensions.mdnotes.placeholder.shortTitle;{"content":"{{bullet}} Short Title: {{field_contents}}", "field_contents": "{{content}}", "link_style": "wiki"}

**Comment by argenos** [comment]
@linxule I won't be adding preferences for each of those, but it's possible to [add any field ](https://argentinaos.com/zotero-mdnotes/docs/placeholders/) to your templates. Keep in mind that you only need to add those preferences if you want to [customize the format](https://argentinaos.com/zotero-mdnotes/docs/formatting/#placeholders).
