### ISSUE TITLE
Format template  fields

### ISSUE THREAD

**Issue by brimwats** [argenos/zotero-mdnotes#46]
**Currently fields are like this:**

```
{{title}}
{{citekey}}
{{related}
{{collections}}
{{tags}}, #zotero-notes
```

**Describe the solution you'd like**
 It would be nice to preformat the template, so it could be like this
```
{{title}}
*{{citekey}}*
*{{related}}*
**{{collections}}**
**{{tags}}**, #zotero-notes
```

**Currently this comes out as:**

![image](https://user-images.githubusercontent.com/49103046/99874390-85865d00-2b9c-11eb-9a54-9d18b7d8d7ac.png)

**Ideally it could be:**

- *Cite key: campbellDickensCholeraBig2019*
- *Related: [[aidenUnchartedBigData2013]]*
- **Topics: [[DigitalHumanities]], [[Big Data]]**
- **Tags:** #Data, #DigitalHumanities, #zotero-notes

**Comment by argenos** [comment]
Hey @brimwats! The formatting should be adjusted in the hidden preferences, not directly in the templates. You can read about that [here](https://argentinaos.com/zotero-mdnotes/docs/formatting/).
