### ISSUE TITLE
Make Item Notes Title and Item Title different

### ISSUE THREAD

**Issue by brimwats1** [argenos/zotero-mdnotes#47]
Currently Item Notes Title and Item Title are the same thing, so if I have

```
{{title}}
{{citekey}}
{{related}}
{{collections}}
{{tags}}, #zotero-notes
```
It shows up as
![image](https://user-images.githubusercontent.com/49103046/99874825-7ce35600-2b9f-11eb-923c-c71b5bc116e1.png)

Later on in my "batch export" it gets to the Zotero Note Template, which is 

```
{{title}}
{{tags}}
{{related}}


{{noteContent}}
```

Rendered as:

![image](https://user-images.githubusercontent.com/49103046/99874839-a8fed700-2b9f-11eb-86a4-1c0ea44f11de.png)

It would be nice if I could make it H2, so:

## Extracted Annotations
Tags: #testtag

However in the advanced config because title and title is the same I cannot specify that I want a H2 header. It looks like you tried to allow this, but it doesn't quite work

![image](https://user-images.githubusercontent.com/49103046/99874890-1dd21100-2ba0-11eb-82e2-e48df60808b3.png)

**Comment by argenos** [comment]
@brimwats could you confirm if you're using the single-file setting? I suspect this is a bug, although I'm not able to reproduce that with the single-file & batch export settings. Could you add a screenshot of the item & notes you're trying to export?

**Comment by argenos** [comment]
Probably also a good idea if you upload the templates you're using! With the default templates, I couldn't reproduce this behaviour.

**Comment by brimwats** [comment]
To be clear, I am **only** using batch export. I but in order to make the batch export "clean" I have to edit each of the following:

## mdnotes template

```
{{title}}
{{citekey}}
{{related}}
{{collections}}
{{tags}}, #zotero-notes

***

##  Zotero links
{{localLibrary}}
{{cloudLibrary}}
{{pdfAttachments}}

***

```

## Zotero Metadata Template

```
## Bibliographic Data
{{itemType}}
{{author}}
{{proceedingsTitle}}
{{date}}
{{url}}
{{DOI}}
{{abstractNote}}

***


```


## Zotero Note Template

```
{{title}}
{{tags}}
{{related}}


{{noteContent}}

```



## Standalone Notes Template
**did not edit or use this**


```

Related to: [[%(metadataFileName)]]

## Notes
-
```

**Comment by argenos** [comment]
Placeholder has been added in 0.2.0. Available for alpha testing here: https://github.com/argenos/zotero-mdnotes/releases/tag/0.2.0-alpha1
