### ISSUE TITLE
Can't get linked pdfs (dropbox) from zotero to show up in exported md file

### ISSUE THREAD

**Issue by agb84** [argenos/zotero-mdnotes#5]
Hi there,
Thanks so much for making this xpi.  I have been able to get this working, but cannot figure out why the links to my pdfs are not showing up in the md note that gets created after batch export.  I have all my pdfs stored in dropbox and linked to the references inside zotero.  I have no trouble accessing the pdfs from inside zotero (I can easily open them in my default app).  Whenever I do an export, the items (notes) under the reference get exported, as does the metadata.  A local link to the citation also gets exported (so if I click on the link in my exported md note in Obsidian, it will open the citation in Zotero).  However no cloud link (e.g. to the pdf of the articles themselves) is never created).  I'm not sure how to get a link to the actual pdf to show up inside my exported notes.  I Have zotfile and Betterbibtex installed and have checked for issues with naming conventions possibly causing issues, but haven't found any.  I'm on the latest version of Zotero and zotero-mdnotes (on Mac).
Side Question:   Is there a way for annotations on pdfs to be auto-extracted and auto-exported into the md note?  
Thanks!

**Comment by argenos** [comment]
> Thanks so much for making this xpi. I have been able to get this working, but cannot figure out why the links to my pdfs are not showing up in the md note that gets created after batch export.

Oh! I don't create links to the PDFs, just the items in the library, this might be easy to add though. 

>  Is there a way for annotations on pdfs to be auto-extracted and auto-exported into the md note?

The extraction part depends on Zotfile, so I haven't checked if it's possible to automate this further. When would the auto-extraction take place? It might be possible to do each time you open Zotero, unless there's a way to tell to Zotero "hey! I'm done highlighting". The other question would be, which PDFs to check  for highlights, all of them? Personally, I don't really need to extract highlights of everything I read. This one seems a bit complex and I'm not sure I can invest time on it, so I would welcome PRs!

For the auto-export, could you go a bit into detail about what you mean by this? Something I'm considering at the moment (since I saw it in Obsidan's forum) is a similar workflow as Better-bibtex to keep exported notes updated when things change in the Zotero side, so there would be no need to re-export to update highlights and annotations. However, this too might take a while to implement.

**Comment by agb84** [comment]
> > Thanks so much for making this xpi. I have been able to get this working, but cannot figure out why the links to my pdfs are not showing up in the md note that gets created after batch export.
> 
> Oh! I don't create links to the PDFs, just the items in the library, this might be easy to add though.
> 
Oh... okay I thought I was doing something wrong.  That would be so helpful if that was added.
> > Is there a way for annotations on pdfs to be auto-extracted and auto-exported into the md note?
> 
> The extraction part depends on Zotfile, so I haven't checked if it's possible to automate this further. When would the auto-extraction take place? It might be possible to do each time you open Zotero, unless there's a way to tell to Zotero "hey! I'm done highlighting". The other question would be, which PDFs to check for highlights, all of them? Personally, I don't really need to extract highlights of everything I read. This one seems a bit complex and I'm not sure I can invest time on it, so I would welcome PRs!
> 
The auto-extraction could take place when the document used to make highlights and annotations is closed inside the program used to make those highlights/annotations.  I realize now that this would be something from Zotfile's side as you mentioned. After reading your reply, I agree this one may not be as important as the idea below.
 
> For the auto-export, could you go a bit into detail about what you mean by this? Something I'm considering at the moment (since I saw it in Obsidan's forum) is a similar workflow as Better-bibtex to keep exported notes updated when things change in the Zotero side, so there would be no need to re-export to update highlights and annotations. However, this too might take a while to implement.

That would be a fantastic feature.  I was thinking more of the implementation that is available for Zettlr.  Zettlr uses a CSL JSON export format when exporting the zotero library (requires pandoc-citeproc). During the export there is an option button to click to select "Keep Updated."  Then, after the zotero library is exported, any changes made to the references inside of Zotero (including the citekey) are automatically pushed to the export file so references stay up-to-date inside Zettlr.  This might have additional benefits in terms of also syncing notes, etc, when there are updates.

**Comment by argenos** [comment]
> During the export there is an option button to click to select "Keep Updated."

That's not Zettlr, it's the Better-Bibtex plugin doing its magic on the Zotero side! 

I just pushed a new version that should add links to the PDFs (through Zotero) in the metadata, so I'll close this issue.
I don't know how much time it would take to add a feature to keep notes updated, so I've opened #6 for that. 

Let me know if you run into any issues!

**Comment by agb84** [comment]
> > During the export there is an option button to click to select "Keep Updated."
> 
> That's not Zettlr, it's the Better-Bibtex plugin doing its magic on the Zotero side!
> 
> I just pushed a new version that should add links to the PDFs (through Zotero) in the metadata, so I'll close this issue.
> I don't know how much time it would take to add a feature to keep notes updated, so I've opened #6 for that.
> 
> Let me know if you run into any issues!

Wow, this is great!  Thanks so much.... Works like a charm.  
There is one very small issue (in the md preferences window now- though I think this may be caused by limitations on Zotero's side).  I cannot see the full screen of the md preferences window in zotero anymore.  The bottom portion of the window extends below my display and the only way to see whats down there is to keep pressing tab (to force the screen to move lower than "Zotero file name suffix" area).  I tried making the window full screen, but still have the issue.  Not sure if that's an issues on Zotero's side though. It's a minor issue though and am more than happy to work around it.  Thanks again for your amazing plugin- it's really quite helpful!
In case you are thinking about adding anything new in the future, one thing that would be super handy is to be able to manually select which pieces of metadata have which style of internal links (e.g. no links, wiki, or markdown).  In my case, I don't need need almost any of the metadata to have an internal link (so I selected the "no link" style).  However, it would be useful to have an option to set an alternate internal link style in the "Tags" section of md preferences (where I would much prefer the "wiki" style of linking).  The hash sign option there is nice, but I personally would prefer the wiki style for tags. 
Thanks again for this plugin :)

**Comment by argenos** [comment]
Could you add a screenshot of the preferences window? I moved a few things around to distribute things horizontally a bit more, since I got some feedback it didn't fit vertically before. Haven't run into this issue myself yet, but this is probably something quick to fix!

**Comment by argenos** [comment]
> In my case, I don't need need almost any of the metadata to have an internal link (so I selected the "no link" style). However, it would be useful to have an option to set an alternate internal link style in the "Tags" section of md preferences (where I would much prefer the "wiki" style of linking). 

This could *potentially* be quick to add, but not for setting the formating of links individual metadata elements. Which ones would you like to have as wiki links? I think I could add a preference that covers your case, and if later on there are more requests to customize this then I can evaluate a better option.

**Comment by agb84** [comment]
> Could you add a screenshot of the preferences window? I moved a few things around to distribute things horizontally a bit more, since I got some feedback it didn't fit vertically before. Haven't run into this issue myself yet, but this is probably something quick to fix!

Thanks so much for looking into this.  Here is the screenshot.  
<img width="847" alt="Screen Shot 2020-08-20 at 5 15 34 PM" src="https://user-images.githubusercontent.com/66561261/90827130-a7f0ac00-e309-11ea-93af-cd1382e6e79c.png">
Best regards,

**Comment by agb84** [comment]
> > In my case, I don't need need almost any of the metadata to have an internal link (so I selected the "no link" style). However, it would be useful to have an option to set an alternate internal link style in the "Tags" section of md preferences (where I would much prefer the "wiki" style of linking).
> 
> This could _potentially_ be quick to add, but not for setting the formating of links of individual metadata elements. Which ones would you like to have as wiki links? I think I could add a preference that covers your case, and if later on there are more requests to customize this then I can evaluate a better option.

Depending on the project I am working on, "Authors", "Topics" or "Related" it would be handy to have a Wiki Link option.  Personally, I am less inclined to use Wiki Links for Type, Date, Date Added, Publication, or DOI (so these are set to "no link").  But yes certainly even just have the wiki option for tags would be immensely helpful!  Thanks again Argenos.

**Comment by argenos** [comment]
Alright, from what I've understood, I only needed to add a "no links" option to type and dates. You can set the links to wiki, and add exceptions for those two fields in the hidden preferences like this:

![image](https://user-images.githubusercontent.com/5426039/91085956-7e5bbb80-e64e-11ea-96c5-f224b5b9d76e.png)

That should result in a note like this: 
![image](https://user-images.githubusercontent.com/5426039/91086153-ca0e6500-e64e-11ea-97fe-fab44ecfccc1.png)

**Comment by agb84** [comment]
> I think that might be a local issue, the links from the notes extracted by Zotfile are to the PDF and the specific page. Do they work for you on the yellow notes within Zotero?

Good question.  I took a look at this...  No, they do not work on the yellow notes within Zotero either. :(
If I edit the link there and remove the page number, the link works again (actually opens the pdf- but is not able to go to the correct page).  There is something about the page number reference that is preventing the link from working at all.

**Comment by agb84** [comment]
> Actually, it seems to be a known "issue", try [this](http://zotfile.com/#changes-in-42).

Thank you for this reference.  I took a look at that.  It looks like there was an update to this issue in  5.0.8.  Unfortunately, this did not fix the issue for me for some reason.  The page number in the link breaks the link.

**Comment by agb84** [comment]
> Alright, from what I've understood, I only needed to add a "no links" option to type and dates. You can set the links to wiki, and add exceptions for those two fields in the hidden preferences like this:
> 
> ![image](https://user-images.githubusercontent.com/5426039/91085956-7e5bbb80-e64e-11ea-96c5-f224b5b9d76e.png)
> 
> That should result in a note like this:
> ![image](https://user-images.githubusercontent.com/5426039/91086153-ca0e6500-e64e-11ea-97fe-fab44ecfccc1.png)

This is brilliant! So helpful :)
This works so well now on my end.  Also loving the extra spacing spread across 3 pages in the preferences window.  I feel bad asking, but... if there was any possible way to add this same option to have "no links" for 'Publication'?   Or perhaps even for 'Author'?  Thank you again!!

**Comment by argenos** [comment]
The checks I added for the exceptions are not great 😅 which is why I was asking where you needed links before. That wouldn't scale well for more options (imagine having to check for each checkmark in the metadata preferences), so I would wait for more requests to change this format.

**Comment by argenos** [comment]
@agb84 Have you given Skim a try? In [Zotfile's documentation](http://zotfile.com/), there is a heading for *Go to annotation*:
> On Mac OS, zotfile works with Preview (the default) and Skim. Preview, however, does not support scripting very well and has certain limitations. Don’t press any keys while the pdf is opening, for example. Skim, an alternative pdf viewer for Mac OS, works much better! Just set the hidden option zotfile.pdfExtraction.openPdfMac_skim to true and zotfile will open the pdf in Skim.

**Comment by linxule** [comment]
@agb84 @argenos 
Seems like this "zotfile.pdfExtraction.openPdfMac_(software name)" (as a string) has been changed:

> -[ZotFile - Advanced PDF management for Zotero](http://zotfile.com/)
> > -Changes in 4.2
> > > -Add wildcard %g for author’s full name (thanks to [QingQYang](https://github.com/QingQYang))
> > > -Support for PDF Expert and other PDF readers on mac to open links in Zotero notes (the hidden option `pdfExtraction.openPdfMac_skim` changed to `pdfExtraction.openPdfMac`. `openPdfMac` is a string with the exact name of the application such as “Preview”, “Skim” or “PDF Expert”).
