### ISSUE TITLE
Change the batch exportation md file name

### ISSUE THREAD

**Issue by icr1001** [argenos/zotero-mdnotes#50]
Thanks for the template version, it is amazing!!

Is there a way to have more control on the batch exportation md file name?
I unchecked "Use the item's citekey as title?" but the title is with hyphens: "This-is-the-title.md". I know that we can edit the prefix and suffix, but I need to store the batch exportation file with something like "<PublicationYear><Author><FullTitleWithSpace>.md", and without changing the bibtext citation key

**Comment by argenos** [comment]
Hi @icr1001, the title might depend a little on your configuration. Are you using markdown links?

**Comment by icr1001** [comment]
> Hi @icr1001, the title might depend a little on your configuration. Are you using markdown links?

Hi @argenos, thanks for your reply, No, I am not using any links (I chose the option ""No links" for the internal links option). And changed the title placeholder to
```
extensions.mdnotes.placeholder.title;{"content":"{{field_contents}}", "field_contents": "{{content}}", "link_style": "no-links"}
```
Is there a way to change the the change the default batch name of the markdown file?

**Comment by argenos** [comment]
Not at the moment! If you choose no links or markdown links, right now file names are substituting spaces with dashes and all lowercase. I'll try to add an option to customize this.

**Comment by icr1001** [comment]
> Not at the moment! If you choose no links or markdown links, right now file names are substituting spaces with dashes and all lowercase. I'll try to add an option to customize this.

Thank you Argenos, this plugin is really useful
