### ISSUE TITLE
Export to markdown creating links even though 'no links' option is selected

### ISSUE THREAD

**Issue by riktross** [argenos/zotero-mdnotes#51]
**Describe the bug**
I have the 'No links' options selected in mdnotes preferences. Still, when I export to markdown, the authors' names have wiki-style links

**To Reproduce**
1. Go to 'Mdnotes preferences'
2. Click on 'Internal Links > No links'
3. Click Ok
4. Select a Zotero item > export to markdown
5. Look at note, author will have links

**Expected behavior**
I expected 'export to markdown' to generate a note with metadata in plain text (with no links)

**Screenshots**
![image](https://user-images.githubusercontent.com/67185930/100499035-c23af100-3166-11eb-91dd-38badf2e227d.png)
![image](https://user-images.githubusercontent.com/67185930/100499116-4ab99180-3167-11eb-9b5b-97ae073c2002.png)

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Zotero version: v5.0.93
 - Mdnotes version: v0.1.2
 - Zotfile version: v5.0.16
 - BetterBibtex version: v5.2.89

**Additional context**
Thanks for all your work argenos, you and your software are really awesome! It would be great if this issue could be resolved, but  even if not, your add-on is still amazing as is 👍

**Comment by argenos** [comment]
@riktross could you show me how your author and topic placeholders are formatted? My suspicion is that the [field format](https://argentinaos.com/zotero-mdnotes/docs/formatting/#placeholders) has wiki links that override that default setting.

**Comment by riktross** [comment]
That solved it! I just corrected the field format and everything is working as I wanted it to! Thanks a lot 😃
