### ISSUE TITLE
author and collections field disobeys link style setting

### ISSUE THREAD

**Issue by linusboyle** [argenos/zotero-mdnotes#52]
The author and collections field does not obey the link style set in the GUI menu. Though I can change it in the hidden setting, I think that's inconvenient at least.

**Comment by argenos** [comment]
You can check #51 for why this is happening. Removing the link-style from the author and collection placeholders will make it obey your default setting. Might modify the default preferences to remove this eventually.

**Comment by linusboyle** [comment]
@argenos yeah thanks, I can make it work. It's just that the setting is not incoherent.
