### ISSUE TITLE
Export md to clipboard

### ISSUE THREAD

**Issue by mikebarkmin** [argenos/zotero-mdnotes#54]
**Is your feature request related to a problem? Please describe.**
I am using Zotero in combination with Obsidian. I used mdnotes to quickly copy over metadata from my Zotero database into my Vault. For this, I am exporting an item of my library to a temporary md file. Afterward, I copy the content of this md file into my vault.

**Describe the solution you'd like**
For me, it would be much faster, if I could not create a md file but copy the md content directly to the clipboard.

**Comment by wanghuibin0** [comment]
I need this capability too. It will be more convenient if mdnotes support exporting md content to clipboard. Hope to use this  capability early.

**Comment by dikti** [comment]
I'd also very much like that, as my workflow currently is
1. annotating the pdf
2. extracting annotations to a note with ZotFile
3. export to a markdown file
4. copy the contents into my Obsidian note
5. delete the temporary file and the link to it inside Zotero

Would be really nice if I could remove 3. and 5. from that list.

**Comment by 00apm** [comment]
This feature would be really useful
