### ISSUE TITLE
Export metadata, highlights and annotation in a single file

### ISSUE THREAD

**Issue by pcuellar** [argenos/zotero-mdnotes#60]
**Issue**
Currently, I can't export in a single file the metadata of a file in Zotero, along with highlights and annotations produced through Zotfile. What this means is me having to export annotations through Zotfile, and metadata through mdnotes separately, and then collate in one file. Time consuming, especially with multiple items.

**Solution**
I would like the ability to export both annotations and metadata together in a single file. The output should be a single .md file containing both pieces of information

**Comment by argenos** [comment]
This is already possible, albeit a bit confusing! I haven't had the time to change to the stable branch and update my settings to give step by step instructions/add screenshots, so, for now, a few pointers:
- Check the `mdnotes` settings and make sure you've selected the single file export
- After having extracted your annotations with Zotfile, choose the "parent" item (the reference itself, not the yellow notes) and use the `Batch export` menu

You can also take a look at #55 in the meantime

**Comment by pcuellar** [comment]
@argenos Thanks for the explanation. I actually was able to get it to produce the file the way I wanted to. I'll write a short post on the Obsidian forum in case folks are also wanting to do something similar.
