### ISSUE TITLE
"change_case" for tags isn't working

### ISSUE THREAD

**Issue by alltagsverstand** [argenos/zotero-mdnotes#61]
Don't know if this might be a bug or if I am just doing something wrong:

when I change "extensions.mdnotes.placeholder.tags" to convert tags to lowercase, this doesn't have any effect after batch export - tags still appear as `#Tag` instead of `#tag`

The complete line looks like this in my setting:

`{"content":"{{field_contents}}", "field_contents": "#{{content}}", "link_style": "no-links", "list_separator":" ", "change_case":"lower", "remove_spaces": "true"}`

**Comment by atraphaxis** [comment]
I had the same problem as you! It turns out it's an error in the documentation rather than an error with the code. In the JSON, it's actually looking for the key "text_case" rather than "change_case". So, in order to make your setting work, it would have to look like the following:

```json
{"content":"{{field_contents}}", "field_contents": "#{{content}}", "link_style": "no-links", "list_separator":" ", "text_case":"lower", "remove_spaces": "true"}
```

**Comment by nistara** [comment]
@jacob-underwood thanks for this solution! I think there's a typo in the code you shared....

`"list_separator":" ", "text_case"` should be `"list_separator": ", ", "text_case"` : 

```
{"content":"{{bullet}} Tags: {{field_contents}}", "field_contents": "#{{content}}", "link_style": "no-links", "list_separator": ", ", "text_case":"lower", "remove_spaces": "true"}
```

At least, that's what I needed to edit to make it work for me!
