### ISSUE TITLE
Export author's last name only (no first name) to leverage unlinked mentions in Obsidian

### ISSUE THREAD

**Issue by Wietsedl** [argenos/zotero-mdnotes#63]
In the template & exported md file, the author is in the fixed format of first + last name. It is created from the creators by the plugin. There's no accessible item field with only the author's last name that one can add.

In different reference styles, the in-text references in scientific papers are only comprised of the last name, not the first name. Being able to choose to export as data only the last name of the author would leverage the 'unlinked mentions' functionality in Obsidian -> from an author's last name we would not only see the direct Linked mentions but also Unlinked mentions, such as a part of the text that was highlighted in the original paper and exported trough the plugin to markdown/Obsidian.

So either a seperate custom field or the option to choose to use first+last name format vs last name only, would leverage the unlinked mentions better!

**Comment by ngirard** [comment]
@Wietsedl, why not adding an alias to your note ?
 i.e. for the author `John Doe`, if you want the corresponding note to be named `Doe.md`, simply add
```
---
aliases: [John Doe]
---
```
at the beginning of the file.

**Comment by Wietsedl** [comment]
hi, thanks for the advice! Reason being that I frequently re-export from Zotero and thus aim to avoid any adaptions in Obsidian itself. Ofcourse I could add '[[Doe]]' in the note in Zotero itself before exporting, true! (but trying to avoid as much as possilbe these type of interruptions in the workflow - ideally keeping it to: annotate@pdf -> extract annotations -> export to md & use it to reference to from other md notes.

**Comment by trungng2006** [comment]
It would also be nice if MDnotes can extend the last-name with in-text citation:
```
aliases
- "Shemla, Meyer, Greer, & Jehn, 2016"
- "Shemla, Meyer, Greer, and Jehn (2016)"
- "Shemla et al., 2016"
- "Shemla et al., (2016)"
```
Use case: if new journal article mentioned the old one that i already put in obsidian, i want it to show up in unlink so i can link them. From this, then i can see how see how different papers have different interpretations of 1 journal article

Further context:
https://discord.com/channels/686053708261228577/722584061087842365/812240728122064907
