### ISSUE TITLE
Ability to access the localized values for fields

### ISSUE THREAD

**Issue by ngirard** [argenos/zotero-mdnotes#65]
I'm interested in lowering the barrier to good knowledge management for non-english speakers.

In this respect, it would be great to be able to access the localized values for fields [such as ItemTypes](https://github.com/zotero/zotero/blob/fd94d731d4ea79ed35db65ac10e0f2c6ccb26637/chrome/locale/fr-FR/zotero/zotero.properties#L403).

Also, links to english terms make little sense to non-english speakers.
For instance, `[[Video recording]]` does'nt make much sense within in a collection of notes in French, as opposed to `[[Enregistrement vidéo]]`.

Cheers

**Comment by argenos** [comment]
I agree that this would be great for non-English notes. Unfortunately, I don't have much time to look into Zotero's code for the localization options, so I would welcome PRs for this!

**Comment by PhilipMottershead** [comment]
This is fairly simple after worked out how it worked as you can use Zotero.getString() to link to the translation service
