### ISSUE TITLE
Ability to localize localLibrary and cloudLibrary

### ISSUE THREAD

**Issue by ngirard** [argenos/zotero-mdnotes#66]
In the same vein as #65, I wish to be able to give non-english labels to the links corresponding to `localLibrary` and `cloudLibrary`.

This is currently impossible, since `Local library` and `Cloud library` are hardcoded within the `getLocalZoteroLink()` and `getCloudZoteroLink()` functions from `content/mdnotes.js`.

**Comment by PhilipMottershead** [comment]
Do you know if these translations are in the translations provided by Zotero/by what key

**Comment by argenos** [comment]
Customizing the text should be possible in 0.2.0 by manually editing the placeholder in the hidden preferences.
