### ISSUE TITLE
Custom templates not recognized v0.1.2

### ISSUE THREAD

**Issue by depth-charge** [argenos/zotero-mdnotes#68]
**Describe the bug**
A template folder has been configured in the preferences pane, but Mdnotes seems not to recognize the templates stored within the root of that directory. As a result, any of the Mdnotes export options within Zotero create markdown files that use the default settings. I've confirmed that the template folder path configured in the Mdnotes preferences is being written to Zotero's internal advanced configuration settings.

**To Reproduce**

These steps assume that an Export directory has already been successfully configured in Mdnotes preferences.

1. Within Zotero, click on ```Tools > Mdnotes preferences```
2. Under the ```Export preferences``` tab, ```Template folder``` click the ```Choose…``` button to select a template folder on the local drive.
3. In the resulting window, navigate to the desired folder, click ```Open``` to select the desired folder. The path to the selected folder will display in the ```Template folder``` field of the preferences pane. Close the preferences window.
4. Create the four default templates required (```Zotero Metadata Template.md```, ```Standalone Note Template.md```, ```Mdnotes Default Template.md```, ```Zotero Note Template```) and save them to the folder configured in step 3. In my case I copied and pasted the default item placeholders in the documentation [here](https://argentinaos.com/zotero-mdnotes/docs/templates/).
5. In Zotero, select an item with attached notes. Right click on the note entry and select ```Export to markdown```.
6. Navigate to the Mdnotes export directory on the local computer. Mdnotes successfully outputs the resulting ```.md``` file for the selected Zotero notes.
7. Open the resulting ```.md``` file in an appropriate text editor. The resulting document uses the default Mdnotes template, and not the custom template configured in step 4.

**Expected behavior**
Mdnotes recognizes the custom template with valid item placeholders and populates the template with the relevant notes content exported from Zotero.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS Big Sur v11.2.1]
 - Zotero version: [v5.0.96-beta.17+d9cf53725]
 - Mdnotes version: [e.g. v0.1.2]
 - Zotfile version: [v5.0.16]
 - BetterBibtex version: [v5.2.117]

**Additional context**

**Comment by depth-charge** [comment]
The custom templates functions work as expected: It helps to modify the default templates if you expect something other than default behavior ;-)

**Comment by johnghill** [comment]
In my case it was the inadvertent addition of a double filename extension to `Mdnotes Default Template.md.md` which prevented `zotero-mdnotes` from using my custom template. Obsidian appends the `.md` extension by default.

**Comment by nerdneilsfield** [comment]
> In my case it was the inadvertent addition of a double filename extension to `Mdnotes Default Template.md.md` which prevented `zotero-mdnotes` from using my custom template. Obsidian appends the `.md` extension by default.

That helps me, thanks!
