### ISSUE TITLE
Differentiate between {{itemtitle}} and {{notetitle}}

### ISSUE THREAD

**Issue by brimwats1** [argenos/zotero-mdnotes#70]
I only use "create full export note" Here's my templates 

Mdnotes Default Template
```
{{title}}
{{citekey}}
{{related}}
{{collections}}
{{tags}}


## Metadata
{{itemType}}
{{author}}
{{proceedingsTitle}}
{{date}}
{{url}}
{{DOI}}
{{abstractNote}}

***

##  Zotero Links
{{localLibrary}}
{{cloudLibrary}}
{{pdfAttachments}}


***
{{noteContent}}

```

Zotero Note Template
```md
{{title}}
{{noteContent}}
```

Basically I would like the {{notecontent}} aka the second {{title}} here to be a H2 (## Title), not a H1 (# Title) in markdown.

**Comment by argenos** [comment]
This should be fixed in 0.2.0.
