### ISSUE TITLE
{{title}} not recognized for cases, missing from generated output

### ISSUE THREAD

**Issue by jonas-sk** [argenos/zotero-mdnotes#73]
**Describe the bug**
When exporting a case, the case name is not recognized as {{title}}, so the title is missing from the Markdown file

**To Reproduce**
1. Create a title that includes `{{title}}` or `%(title)`
2. Create an item of type "case" in Zotero and add a title
3. Click "Mdnotes" > "Export to markdown"
4. Open the markdown file and notice the missing titles

**Expected behavior**
The case name should be recognized as title and be included in the generated files, based on the template. AFAIK from working on Zotero pickers, case names are recognized as titles internally.

**Desktop:**
 - OS: MacOS Big Sur
 - Zotero version: v5.0.96
 - Mdnotes version: v0.1.3
 - Zotfile version: v5.0.16
 - BetterBibtex version: v5.2.124

**Additional context**

**Comment by argenos** [comment]
Hi @jonas-sk, does it work if you add `{{caseName}}`? The full list of fields as exported from Zotero is [here](https://api.zotero.org/itemFields?pprint=1) and how you can format them is [here](https://argentinaos.com/zotero-mdnotes/docs/formatting/#placeholders).

**Comment by jonas-sk** [comment]
It works when I include it! Although it is somewhat awkward to include in templates since an item can either have a title or a case name.

Not sure why, but wildcards seem to have stopped working now (I used them for aliases in Obsidian). Removing {{caseName}} doesn't help. Maybe it's connected to me modifying about:config: I added entries for caseName and docketNumber and changed the entries for the bullet and for tags.

**Comment by argenos** [comment]
It’s alright if you include both as placeholders in the template; if nothing matches them they will be ignored. Wildcards are NOT ignored however.

Check if your new entries are valid JSON! If they aren’t, it will probably stop the export!

**Comment by jonas-sk** [comment]
Thanks! The placeholders I used are %(title), %(author) or %(caseName), but no placeholders work anymore. They simply stopped working after I changed the above about:config settings. And the Zotero items all have the respective fields filled out.

![image](https://user-images.githubusercontent.com/7535016/110249892-ce5df800-7f78-11eb-81b7-9520e53b0de8.png)

**Comment by argenos** [comment]
I suspect there is a problem with your modified JSON strings, have you checked them in an online JSON validator?

**Comment by argenos** [comment]
I don't see anything immediately obvious from your screenshot (it looks like valid JSON). Does it also happen if you remove the docketNumber? I would try modifying one at a time to catch which one is causing problems.
