### ISSUE TITLE
Github pop-up says .xpi file will not download because plug-in file "appears to be corrupted."

### ISSUE THREAD

**Issue by pzoni60** [argenos/zotero-mdnotes#75]
**Describe the bug**
Github pop-up says .xpi file will not download because plug-in file "appears to be corrupted."

**To Reproduce**
1. Click on mdnotes .xpi link
2. See error

**Expected behavior**
Download to my download folder

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Zotero version: [v5.96
 - Mdnotes  NOT INSTALLED YET
 - Zotfile version: [v5.0.16]
 - BetterBibtex : [v5.2.124]

**Additional context**

**Comment by argenos** [comment]
Hi @pzoni60! Since `xpi` files used to be also for Firefox plugins, when you click on them it might try to get installed. Try right clicking and using the `Save as` menu.

**Comment by pzoni60** [comment]
Thank you @argenos !!!!

I've been covertly scouring the Obsidian forum and discord areas in my
efforts to learn about Obsidian and how to integrate this amazing package
with Zotero (which I've been using Zotero for a couple of years).

You, sir, are a patient and generous human being.  I've observed your
timely replies to rookies like me, as well as your collaboration with other
skilled Obsidians.  It's people like you that give me hope and fuel the
collaboration and support that Obsidian has become known for.  I'm
especially grateful for your work on the MD-Notes plug-in which, as a
"citation" guy, I'm hoping will accommodate my workflow.

Even if it doesn't.

Thank you,
Paul
