### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by ionm** [argenos/zotero-mdnotes#76]
Is there a way for defining shortcuts in mdnotes, or through Zutilo?

**Comment by carbeer** [comment]
Yes, Zutilo supports Mdnotes. If you go to "Tools" --> "Zutilo preferences" you will find a few options to customize shortcuts.
![image](https://user-images.githubusercontent.com/20532493/124912440-3dfaf700-dfee-11eb-9eb1-397f109f3fbe.png)
