### ISSUE TITLE
Export all highlights as separate notes!

### ISSUE THREAD

**Issue by twilightfades0** [argenos/zotero-mdnotes#78]
**Is your feature request related to a problem? Please describe.**

No, just a me-problem 😅

**Describe the solution you'd like**

Being able to **_export all the highlights from a paper as separate notes_** which all link back to the source note would be AMAZING! 

**Additional context**

I'm currently doing this manually and it's a multi-day project ;__;.  I'm doing a few long-term academic research projects and using Obsidian as a tool to let me keep track of information and build up evidence from many sources (not to write like so many other obsidian users seem to), fwiw.  After this paper I'll switch to the by-highlight-color export option for now, but I'd be super grateful for the option of exporting them all separately!

**Comment by ffeurchau** [comment]
Also having this issue! Did you ever find a solution?
