### ISSUE TITLE
List format choices 

### ISSUE THREAD

**Issue by linxule** [argenos/zotero-mdnotes#8]
Would it be possible to choose the format for markdown lists? Currently, we have "*". It would be great to choose "-" for unordered lists as well. Also, some might find numbered lists and task/to-do lists helpful.

**Comment by argenos** [comment]
Right now the formatting is a bit hardcoded, and sort of an all-or-nothing kind of deal. Switching everything to `-` or numbered lists wouldn't be a problem and could be relatively quick to add, but todos don't make sense everywhere. Do you have sections in mind where you would want those?

**Comment by linxule** [comment]
It might be useful to have a general note format/formatting tab. A couple of examples come to mind: 

1. The implementation by @gitmurf for the [roam highlighter](https://github.com/GitMurf/roam-highlighter)
<img width="346" alt="20200910151741@2x" src="https://user-images.githubusercontent.com/43122877/92744182-27a5ef80-f379-11ea-959d-7a2efb728262.png">

2. The implementation in [Highlights App for Mac](https://highlightsapp.net/features/)
<img width="310" alt="20200910152241@2x" src="https://user-images.githubusercontent.com/43122877/92744567-80758800-f379-11ea-8468-3281a3a3cc0c.png">

On a side note, I was wondering if there could be a way to assign "names" to annotation colors and types (much like in Highlights App for Mac). It seems that the customization might be possible by manually changing the settings for Zotfile annotation extraction.




<img width="443" alt="20200910152747@2x" src="https://user-images.githubusercontent.com/43122877/92745354-3345e600-f37a-11ea-8987-a3496d6e3f04.png">

**Comment by argenos** [comment]
Thanks for the examples! I'll take a look as soon as I can!

For the last bit with the colors, you can already do with Zotfile, so I would leave that out of the formatting.

**Comment by linxule** [comment]
Thanks for the note! Would you be able to point me to the settings where I could change the names of color categories? I [tried to manually change the name and text replacements](Zotero/ZotfileAnnotation.css) but haven't able to achieve the goal. Your help is much appreciated!

**Comment by argenos** [comment]
Actually, you're right, it seems that only works for the annotations and is not compatible if you split different highlight colors into different notes. I'll definitely add it as well!

**Comment by linxule** [comment]
That would be a great enhancement! Looking forward to it!

**Comment by argenos** [comment]
@linxule I've partially adressed this in #35 for v0.1.0 which I'll probably release the new version on the weekend. There is an xpi in the linked PR in case you want to test beforehand.

Could you please open a separate issue for the color dictionary? Thanks!

**Comment by linxule** [comment]
Thank you so much for adding the option for the list format!
