### ISSUE TITLE
Markdown Conversion of HTML Blockquotes does not work

### ISSUE THREAD

**Issue by csducate** [argenos/zotero-mdnotes#82]
**Describe the bug**
When annotations are marked as `<blockquote></blockquote>`, they are not exported with `>` appended and so do not convert to markdown blockquote. Lines with quotations, however, *do* convert to markdown blockquotes.

Maybe it's operator error, but I followed someone's walkthrough step by step and cannot get the same output as them.

**To Reproduce**
1. Extract annotations from PDF using Zotfile (format: `<blockquote><p> "%(content)" (%(cite))</p></blockquote>`)
    - Note: I have tried moving around the `<blockquote>` tag and removing the quotes around `%(content)`
<img width="1109" alt="Screen Shot 2021-03-30 at 10 26 16 AM" src="https://user-images.githubusercontent.com/48921940/113005437-77e07580-9142-11eb-915f-e77856e592cf.png">

2. Check source code for annotation; looks fine
<img width="629" alt="Screen Shot 2021-03-30 at 10 27 32 AM" src="https://user-images.githubusercontent.com/48921940/113005529-8e86cc80-9142-11eb-822f-f17e388b8efe.png">

3. Right click on annotation note > Mdnotes > Export to markdown
4. File saves to Obsidian directory
5. Open file and no block quotes
![Screen Shot 2021-03-30 at 10 28 48 AM](https://user-images.githubusercontent.com/48921940/113005813-c8f06980-9142-11eb-8cea-9ba1fad7fcbf.png)

**Expected behavior**
Items marked with blockquote HTML tags would be blockquotes in MD.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - Zotero version: v5.0.96.1
 - Mdnotes version: v0.1.3
 - Zotfile version: v5.0.16
 - BetterBibtex version: v5.2.141

**Comment by argenos** [comment]
I think this should be fixed on the next release, could you try the pre-release available here: https://github.com/argenos/zotero-mdnotes/releases

**Comment by csducate** [comment]
The pre-release works perfectly! Thank you!

**Comment by argenos** [comment]
Glad to hear it!
