### ISSUE TITLE
[alpha 0.20.0 v4] No standalone note created.

### ISSUE THREAD

**Issue by lkhphuc** [argenos/zotero-mdnotes#83]
**Describe the bug**
Standalone note not created in version alpha 0.20.0 v4.

**To Reproduce**
1. Go to zotero item
2. Right click "Create standalone note"
3. Nothing show up in both Zotero and the actual files in Obsidian.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Zotero version: 5.0.97-beta.15+205fe7f03
 - Mdnotes version: 0.20.0 v4 pre-release
 - Zotfile version: [v5.0.16]
 - BetterBibtex version: [v5.2.84]

**Comment by xulei-shl** [comment]
+1

-  if zotero item has pdf Attachments, no mdnotes file exported

OS: MacOS Big Sur
Zotero version: 5.0.97-beta.15+205fe7f03
Zotfile version: [v5.0.16]
Mdnotes version: v0.1.3
BetterBibtex version: [v5.2.135]

**Comment by argenos** [comment]
I have not tested this on the Zotero beta, so I don't know if there are any breaking changes on their latest versions. If you can test on the stable Zotero version, could you let me know if it also happens there?

**Comment by lkhphuc** [comment]
I tested with zotero `5.0.96.1` in a new database and still no standalone note is created.

**Comment by argenos** [comment]
@lkhphuc thanks for testing! Is it only the standalone note that is not created? Do all the other menus work as expected?

**Comment by lkhphuc** [comment]
Yep, Create full export note and export to markdown option works fine for me.

**Comment by datavistics** [comment]
Im not getting the page 
![image](https://user-images.githubusercontent.com/22736772/118256880-04f74800-b4bf-11eb-9ed3-82c4f055e4de.png)
exported as a link.
