### ISSUE TITLE
Allow more metadata in filename

### ISSUE THREAD

**Issue by Jmuccigr** [argenos/zotero-mdnotes#94]
**Is your feature request related to a problem? Please describe.**
I like to include the item (or at least the short version) in the filename of my notes for that file.

**Describe the solution you'd like**
A way to add metadata other than the cite key to an exported filename. This might work in the suffix field.

**Additional context**

**Comment by danieltomasz** [comment]
Currently, the plugin uses either citekey or title of Zotero item.
My citekys are [author][year], I would like to add the name of the article to the exported note.
Now I could either add cite key or the name of the article.

The more general solution of my problem -  allows more metadata to use in a  template in the filename.
The format to specify templates may be similar to those used by the Citations Obsidian plugin
(I would like to add new elements  not only as suffix or prefix)
like
```
@{{citekey}} {{title}}
```
or
```
@{{citekey}} - annotations - {{title}}
```

**Comment by Ir1d** [comment]
One should modify https://github.com/argenos/zotero-mdnotes/blob/master/content/mdnotes.js#L474 this line I think
