### ISSUE TITLE
Attach Obsidian URI when creating notes

### ISSUE THREAD

**Issue by knavynde** [argenos/zotero-mdnotes#99]
**Is your feature request related to a problem? Please describe.**
I noticed some code in mdnotes.js that could add Obsidian URIs as an attachment after exporting a note. It was disabled by preferences that are not yet implemented in the options. This was a feature I was looking for, so I went ahead and finished it, as described below. I'm happy to make a pull request, but I want to make sure there was no specific reason it hasn't been finished.

**Describe the solution you'd like**
I added two options to the preferences file, both just implementing preferences referenced in mdnotes.js. One is a checkbox for enabling saving an Obsidian URI. The other is a textbox where the user can input the name of their vault. In principle, you could probably have a dialog to select a folder containing an obsidian vault and parse out the name, but I haven't looked into that yet. Right now, it's just a raw textbox. 

I also fixed a bug preventing the filename from being parsed properly on Windows

**Additional context**

**Comment by argenos** [comment]
This is already available! See https://argentinaos.com/zotero-mdnotes/docs/next/advanced/hidden-prefs

**Comment by argenos** [comment]
I've closed this since I don't plan to add editor-specific preferences to the preference window.

**Comment by knavynde** [comment]
Thanks. I appreciate that you don't want to pollute the main settings page with editor specific preferences. 

There's still the bug with file path parsing that I fixed, I'll go ahead and make a PR for that.

One idea you might consider is to add an "integrations" panel or something of the like to the settings panel. It seems a shame to have all this code only to be covered and hidden from those not technically inclined enough to scour the docs for hidden settings. Many other apps handle integrations through a dedicated panel, so there's lots of precident. And it might encourage further integration with other services. Apps are made far better by the ability to talk to each other!

Happy to write up the code for that if you're interested.

**Comment by argenos** [comment]
> There's still the bug with file path parsing that I fixed, I'll go ahead and make a PR for that.

Thanks! Happy to review that!

> One idea you might consider is to add an "integrations" panel or something of the like to the settings panel. It seems a shame to have all this code only to be covered and hidden from those not technically inclined enough to scour the docs for hidden settings. Many other apps handle integrations through a dedicated panel, so there's lots of precident. And it might encourage further integration with other services. Apps are made far better by the ability to talk to each other!
> 
> Happy to write up the code for that if you're interested.

My main point here is that not all people using `mdnotes` are Obsidian users, therefore those settings should remain optional, separate and hidden unless the user wants to access them. I don't think the hidden preferences are particularly difficult, especially if they are well documented, but I agree that it will make it easier for other users to discover them if there is a GUI. 

I am not a fan of Zotero's UI work, and developing/maintaining that code is not on my priority list. That being said, I'd be willing to review a PR for that if you're up for it!

**Comment by knavynde** [comment]
That's completely fair, and I'm definitely not asking you to go out of your scope. 

I have a bit of code already written, so I'll see what I can come up with.

**Comment by 1qzhworld** [comment]
> This is already available! See https://argentinaos.com/zotero-mdnotes/docs/next/advanced/hidden-prefs

Hi, argenos. I had set the vault string in Zotero's preference and enable the attach_obsidian_uri (and set the 'New link format' as "Shortest path when possible", though I think this is unrelated)

However, I got an obsidian uri with full path but the uri file with file=.  That is
I got: obsidian://open?vault=test&file=D:\test\openthis
Supposed link:  obsidian://open?vault=test&file=openthis
I can open by:  obsidian://open?vault=test&path=D:\test\openthis (this means the path is correct)

I am not sure where can I set "Shortest path" as suggested in the link https://argentinaos.com/zotero-mdnotes/docs/next/advanced/hidden-prefs
